-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "DEATHKNIGHT_FROST_WOTLK_PRE_LOONBIS",
                name = "PRE Deathknight Frost - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41386, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42645, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 34388, enchantId = 50335, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 37647, enchantId = 47898, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39617, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 41355, enchantId = 60616, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39618, enchantId = 60668, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40688, enchantId = 41611, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37193, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44306, enchantId = 34007, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 42642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 44935, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 41383, enchantId = 53343, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40715, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T7_LOONBIS",
                name = "T7 Deathknight Frost - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 44006, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40557, enchantId = 50335, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 47898, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40550, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40330, enchantId = 60616, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40552, enchantId = 60668, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40278, enchantId = 41611, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40556, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40591, enchantId = 34007, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40075, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 43993, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40431, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T8_LOONBIS",
                name = "T8 Deathknight Frost - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46115, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45459, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46117, enchantId = 50335, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 46032, enchantId = 47898, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46111, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45663, enchantId = 60616, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45643, enchantId = 60668, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45241, enchantId = 41611, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45134, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45599, enchantId = 34007, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45534, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_PRE_WOWHEAD",
                name = "PRE Deathknight Frost - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 48503, enchantId = 59954, gemIds = {41398, 49110}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45459, enchantId = 0, gemIds = {40111}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 48505, enchantId = 59934, gemIds = {40111}, notes = "", source = "wowhead" },
                    BACK = { itemId = 47320, enchantId = 47898, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 48501, enchantId = 60692, gemIds = {40111, 42142}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 47253, enchantId = 44575, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 48502, enchantId = 54999, gemIds = {40111}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 47268, enchantId = 0, gemIds = {40111, 40111}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 45982, enchantId = 60582, gemIds = {40111, 40111}, notes = "", source = "wowhead" },
                    FEET = { itemId = 47312, enchantId = 55016, gemIds = {40111}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 47252, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45534, enchantId = 0, gemIds = {40111}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 47303, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 46097, enchantId = 53343, gemIds = {42142}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 46097, enchantId = 53344, gemIds = {42142}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 'pre' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T7_WOWHEAD",
                name = "T7 Deathknight Frost - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 44006, enchantId = 59954, gemIds = {41398, 42702}, notes = "", source = "wowhead" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {39996}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 40557, enchantId = 59934, gemIds = {39996}, notes = "", source = "wowhead" },
                    BACK = { itemId = 40403, enchantId = 47898, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 40550, enchantId = 60692, gemIds = {39996, 39996}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 40330, enchantId = 44575, gemIds = {39996}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 40552, enchantId = 54999, gemIds = {39996}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 40278, enchantId = 54793, gemIds = {39996, 39996}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 40556, enchantId = 60582, gemIds = {39996, 39996}, notes = "", source = "wowhead" },
                    FEET = { itemId = 40591, enchantId = 55016, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 40075, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 43993, enchantId = 0, gemIds = {39996}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 40256, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 40189, enchantId = 53343, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 40189, enchantId = 53344, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't7' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T8_WOWHEAD",
                name = "T8 Deathknight Frost - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46115, enchantId = 59954, gemIds = {41398, 42702}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45459, enchantId = 0, gemIds = {39996}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 46117, enchantId = 59934, gemIds = {39996}, notes = "", source = "wowhead" },
                    BACK = { itemId = 46032, enchantId = 47898, gemIds = {39996, 39996}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 46111, enchantId = 60692, gemIds = {39996, 39996}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 45663, enchantId = 44575, gemIds = {39996}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 46113, enchantId = 54999, gemIds = {39996}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 45241, enchantId = 54793, gemIds = {42142, 42142, 42142}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 45134, enchantId = 60582, gemIds = {39996, 39996, 39996}, notes = "", source = "wowhead" },
                    FEET = { itemId = 45599, enchantId = 55016, gemIds = {39996, 39996}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 45608, enchantId = 0, gemIds = {39996}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45534, enchantId = 0, gemIds = {39996}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 46097, enchantId = 53343, gemIds = {39996}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 46097, enchantId = 53344, gemIds = {39996}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't8' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T9_WOWHEAD",
                name = "T9 Deathknight Frost - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48493, enchantId = 59954, gemIds = {41398, 40142}, notes = "", source = "wowhead" },
                    NECK = { itemId = 47458, enchantId = 0, gemIds = {40142}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 48495, enchantId = 59934, gemIds = {42142}, notes = "", source = "wowhead" },
                    BACK = { itemId = 47548, enchantId = 55002, gemIds = {42142}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 48491, enchantId = 60692, gemIds = {49110, 42142}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 45663, enchantId = 44575, gemIds = {40111}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 47492, enchantId = 54999, gemIds = {40111, 40111}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 45241, enchantId = 0, gemIds = {40111, 40111, 40111}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 48494, enchantId = 60582, gemIds = {40142, 40111}, notes = "", source = "wowhead" },
                    FEET = { itemId = 45599, enchantId = 55016, gemIds = {40111, 40111}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 47413, enchantId = 0, gemIds = {40142}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45534, enchantId = 0, gemIds = {40111}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 47464, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 47475, enchantId = 53343, gemIds = {40111}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 47475, enchantId = 53344, gemIds = {40111}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't9' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T10_WOWHEAD",
                name = "T10 Deathknight Frost - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51312, enchantId = 59954, gemIds = {41398, 40117}, notes = "", source = "wowhead" },
                    NECK = { itemId = 54581, enchantId = 0, gemIds = {40143}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 51314, enchantId = 59934, gemIds = {40117}, notes = "", source = "wowhead" },
                    BACK = { itemId = 47548, enchantId = 47898, gemIds = {40117}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 51310, enchantId = 60692, gemIds = {42153, 49110}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 50670, enchantId = 44575, gemIds = {40117}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 50675, enchantId = 54999, gemIds = {40117, 40117}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {40143, 42153, 40117}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 51313, enchantId = 60582, gemIds = {42153, 40117}, notes = "", source = "wowhead" },
                    FEET = { itemId = 54578, enchantId = 55016, gemIds = {40117, 40117}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 52572, enchantId = 0, gemIds = {40143}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 50693, enchantId = 0, gemIds = {40143}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 50737, enchantId = 53343, gemIds = {40117}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 50737, enchantId = 53344, gemIds = {40117}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't10' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Deathknight Frost - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41386, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 42645, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34388, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 37647, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39617, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 41355, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40688, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37193, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 43402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 44935, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37642, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 41383, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 44250, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40715, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T9_BISTOOLTIP",
                name = "T9 Deathknight Frost - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48488, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 45459, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48486, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47547, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48490, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 45663, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 47240, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 45241, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48487, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47154, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 46966, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47920, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47526, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47526, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T10_BISTOOLTIP",
                name = "T10 Deathknight Frost - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51312, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50728, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51314, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47547, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51310, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50670, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51311, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51817, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50639, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 52572, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50693, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50672, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_RS_BISTOOLTIP",
                name = "RS Deathknight Frost - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51312, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 54581, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51314, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47547, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51310, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54559, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51311, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51817, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54578, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 52572, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50693, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40207, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_PRE",
                name = "Deathknight Frost - WOTLK_PRE",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T7",
                name = "Deathknight Frost - WOTLK_T7",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T8",
                name = "Deathknight Frost - WOTLK_T8",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T9",
                name = "Deathknight Frost - WOTLK_T9",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Thassarian's Helmet of Triumph (H)", "SHOULDER: Thassarian's Shoulderplates of Triumph (H)", "BACK: Varian's Furor (H)", "CHEST: Thassarian's Battleplate of Triumph (H)", "HANDS: Gloves of Bitte Reprisal (H)", "LEGS: Thassarian's Legplates of Triumph (H)", "FEET: Greaves of the 7th Legion (H)", "RING1: Band of the Violent Temperment (H)", "RING2: Carnivorous Band (H)", "TRINKET1: Death's Verdict (H)", "MAINHAND: Remorseless (H)", "OFFHAND: Remorseless (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T10",
                name = "Deathknight Frost - WOTLK_T10",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Varian's Furor (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_FROST_WOTLK_T10_PROGRESS",
                name = "Deathknight Frost - WotLK T10 Progression",
                class = "DEATHKNIGHT",
                spec = "Frost",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Varian's Furor (H)", "TRINKET2: Death's Verdict (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
