-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "PALADIN_HOLY_CLASSIC_PRE",
                name = "Paladin Holy - CLASSIC_PRE",
                class = "PALADIN",
                spec = "Holy",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_CLASSIC_T1",
                name = "Paladin Holy - CLASSIC_T1",
                class = "PALADIN",
                spec = "Holy",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_CLASSIC_T2",
                name = "Paladin Holy - CLASSIC_T2",
                class = "PALADIN",
                spec = "Holy",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_CLASSIC_T25",
                name = "Paladin Holy - CLASSIC_T25",
                class = "PALADIN",
                spec = "Holy",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_CLASSIC_T3",
                name = "Paladin Holy - CLASSIC_T3",
                class = "PALADIN",
                spec = "Holy",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_TBC_PRE",
                name = "Paladin Holy - TBC_PRE",
                class = "PALADIN",
                spec = "Holy",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 32084, enchantId = 0, gemIds = {25901, 24047}, notes = "", source = "wowhead" },
                    NECK = { itemId = 29374, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 27775, enchantId = 0, gemIds = {24029, 24057}, notes = "", source = "wowhead" },
                    BACK = { itemId = 29354, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 29522, enchantId = 0, gemIds = {24057, 24047, 24057}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 29523, enchantId = 0, gemIds = {24047}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 27457, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 29524, enchantId = 0, gemIds = {24057, 24047}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30543, enchantId = 0, gemIds = {24029, 24047, 24057}, notes = "", source = "wowhead" },
                    FEET = { itemId = 27411, enchantId = 0, gemIds = {24029, 24057}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 29373, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29169, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 30841, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32451, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 29267, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 28296, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                conflicts = {"RING1: Ring of Convalescence"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PALADIN_HOLY_TBC_T4",
                name = "Paladin Holy - TBC_T4",
                class = "PALADIN",
                spec = "Holy",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_TBC_T5",
                name = "Paladin Holy - TBC_T5",
                class = "PALADIN",
                spec = "Holy",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_TBC_T6_LOONBIS",
                name = "T6 Paladin Holy - LoonBiS TBC",
                class = "PALADIN",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 30988, enchantId = 0, gemIds = {32195, 25901}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32370, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 30996, enchantId = 0, gemIds = {32195, 32195}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32524, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 30992, enchantId = 0, gemIds = {32216, 32219, 32219}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 30862, enchantId = 0, gemIds = {32195}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 30112, enchantId = 0, gemIds = {32195, 32195}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30897, enchantId = 0, gemIds = {32195, 32195}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30994, enchantId = 0, gemIds = {32216}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32243, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32528, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 32238, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 32496, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32500, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 32255, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 28592, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"loonbis"},
                notes = "Phase 3 data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PALADIN_HOLY_TBC_T6",
                name = "Paladin Holy - TBC_T6",
                class = "PALADIN",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_TBC_T6_SWP",
                name = "Paladin Holy - TBC Sunwell (BiS)",
                class = "PALADIN",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_WOTLK_PRE_LOONBIS",
                name = "PRE Paladin Holy - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 44949, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42647, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37673, enchantId = 50336, gemIds = {40012}, notes = "", source = "loonbis" },
                    BACK = { itemId = 34242, enchantId = 47898, gemIds = {40012}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39629, enchantId = 60692, gemIds = {40012}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37788, enchantId = 44555, gemIds = {40012}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39632, enchantId = 54999, gemIds = {40012}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40691, enchantId = 41611, gemIds = {40012}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37362, enchantId = 41604, gemIds = {40012}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44202, enchantId = 55016, gemIds = {40012}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 44283, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37169, enchantId = 27968, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40700, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T7_LOONBIS",
                name = "T7 Paladin Holy - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40298, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40573, enchantId = 50336, gemIds = {40012}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 47898, gemIds = {40012}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40569, enchantId = 60692, gemIds = {40012}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40332, enchantId = 44555, gemIds = {40012}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40570, enchantId = 54999, gemIds = {40012}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40259, enchantId = 41611, gemIds = {40012}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40572, enchantId = 41604, gemIds = {40012}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40592, enchantId = 55016, gemIds = {40012}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 27968, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40401, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T8_LOONBIS",
                name = "T8 Paladin Holy - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46180, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45443, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46182, enchantId = 50336, gemIds = {40012}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45486, enchantId = 47898, gemIds = {40012}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45445, enchantId = 60692, gemIds = {40012}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45460, enchantId = 44555, gemIds = {40012}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46179, enchantId = 54999, gemIds = {40012}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45616, enchantId = 41611, gemIds = {40012}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46181, enchantId = 41604, gemIds = {40012}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45537, enchantId = 55016, gemIds = {40012}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45614, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 46051, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46017, enchantId = 27968, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45470, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Paladin Holy - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 44296, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40681, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37655, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39629, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37788, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39632, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37362, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 44283, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37169, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40700, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T9_BISTOOLTIP",
                name = "T9 Paladin Holy - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47144, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47552, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 47147, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 45460, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 45665, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47924, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47067, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 46986, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47224, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 45614, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 46051, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T10_BISTOOLTIP",
                name = "T10 Paladin Holy - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51272, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51273, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50680, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50721, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50650, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 49891, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 46051, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_RS_BISTOOLTIP",
                name = "RS Paladin Holy - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51272, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51273, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50680, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54584, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50650, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 54587, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 49891, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54586, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 46051, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40705, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_HOLY_WOTLK_PRE",
                name = "Paladin Holy - WOTLK_PRE",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T7",
                name = "Paladin Holy - WOTLK_T7",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T8",
                name = "Paladin Holy - WOTLK_T8",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T9",
                name = "Paladin Holy - WOTLK_T9",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Turalyon's Headpiece of Triumph (H)", "NECK: Wail of the Val'kyr (H)", "SHOULDER: Turalyon's Spaulders of Triumph (H)", "BACK: Jaina's Radiance (H)", "CHEST: Breastplate of the Frozen Lake (H)", "WAIST: Belt of the Frozen Reach (H)", "LEGS: Legplates of Failing Light (H)", "FEET: Boots of the Courageous (H)", "RING1: Ring of the Darkmender (H)", "OFFHAND: Bastion of Purity (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T10",
                name = "Paladin Holy - WOTLK_T10",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_HOLY_WOTLK_T10_PROGRESS",
                name = "Paladin Holy - WotLK T10 Progression",
                class = "PALADIN",
                spec = "Holy",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
