-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "WARRIOR_PROTECTION_CLASSIC_PRE",
                name = "Warrior Protection - CLASSIC_PRE",
                class = "WARRIOR",
                spec = "Protection",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_CLASSIC_T1",
                name = "Warrior Protection - CLASSIC_T1",
                class = "WARRIOR",
                spec = "Protection",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_CLASSIC_T2",
                name = "Warrior Protection - CLASSIC_T2",
                class = "WARRIOR",
                spec = "Protection",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_CLASSIC_T25",
                name = "Warrior Protection - CLASSIC_T25",
                class = "WARRIOR",
                spec = "Protection",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_T6_LOONBIS",
                name = "T6 Warrior Protection - LoonBiS TBC",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32521, enchantId = 35443, gemIds = {25896}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32362, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 33732, enchantId = 0, gemIds = {24067}, notes = "", source = "loonbis" },
                    BACK = { itemId = 34010, enchantId = 34004, gemIds = {24067}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 33728, enchantId = 27960, gemIds = {24067}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 33813, enchantId = 27914, gemIds = {24067}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32280, enchantId = 25072, gemIds = {24067}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24067}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 33731, enchantId = 0, gemIds = {24067}, notes = "", source = "loonbis" },
                    FEET = { itemId = 33812, enchantId = 34008, gemIds = {24067}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 30834, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29296, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 31858, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32254, enchantId = 20034, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32375, enchantId = 34009, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "WARRIOR_PROTECTION_CLASSIC_T3",
                name = "Warrior Protection - CLASSIC_T3",
                class = "WARRIOR",
                spec = "Protection",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_PRE",
                name = "Warrior Protection - TBC_PRE",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 28180, enchantId = 0, gemIds = {24033, 25896}, notes = "", source = "wowhead" },
                    NECK = { itemId = 29386, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 32073, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    BACK = { itemId = 27804, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 28205, enchantId = 0, gemIds = {24033, 24033, 24033}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 28996, enchantId = 0, gemIds = {24033}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 27475, enchantId = 0, gemIds = {24033, 24033}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 29238, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 29184, enchantId = 0, gemIds = {24033, 24033, 24033}, notes = "", source = "wowhead" },
                    FEET = { itemId = 28997, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 30834, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29384, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 23836, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 23835, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 28438, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 29266, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 34622, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                conflicts = {"RELIC: Veteran's Musket"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_T4",
                name = "Warrior Protection - TBC_T4",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_T5",
                name = "Warrior Protection - TBC_T5",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_T6_LOONBIS",
                name = "T6 Warrior Protection - LoonBiS TBC",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    NECK = { itemId = 32362, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 33732, enchantId = 35439, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 34010, enchantId = 34004, gemIds = {}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 33728, enchantId = 27960, gemIds = {}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 33813, enchantId = 27914, gemIds = {}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32280, enchantId = 25072, gemIds = {}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 33731, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    FEET = { itemId = 33812, enchantId = 34008, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32254, enchantId = 20034, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32375, enchantId = 34009, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_T6",
                name = "Warrior Protection - TBC_T6",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_TBC_T6_SWP",
                name = "Warrior Protection - TBC Sunwell (BiS)",
                class = "WARRIOR",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_PRE_LOONBIS",
                name = "PRE Warrior Protection - LoonBiS WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42549, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 34389, enchantId = 44957, gemIds = {40008}, notes = "", source = "loonbis" },
                    BACK = { itemId = 37197, enchantId = 55002, gemIds = {40008}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39611, enchantId = 60692, gemIds = {40008}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37620, enchantId = 62256, gemIds = {40008}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 37645, enchantId = 63770, gemIds = {40008}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 34547, enchantId = 0, gemIds = {40008}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 43500, enchantId = 50965, gemIds = {40008}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44895, enchantId = 47901, gemIds = {40008}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 34213, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37186, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37401, enchantId = 59619, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 43085, enchantId = 62202, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 41168, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T7_LOONBIS",
                name = "T7 Warrior Protection - LoonBiS WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40546, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40387, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 39704, enchantId = 44957, gemIds = {40008}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40203, enchantId = 60692, gemIds = {40008}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40545, enchantId = 63770, gemIds = {40008}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40589, enchantId = 50965, gemIds = {40008}, notes = "", source = "loonbis" },
                    FEET = { itemId = 39717, enchantId = 47901, gemIds = {40008}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40370, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40402, enchantId = 59619, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 41168, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T8_LOONBIS",
                name = "T8 Warrior Protection - LoonBiS WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    NECK = { itemId = 45485, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46167, enchantId = 44957, gemIds = {40008}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45496, enchantId = 55002, gemIds = {40008}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46162, enchantId = 60692, gemIds = {40008}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45111, enchantId = 62256, gemIds = {40008}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45487, enchantId = 63770, gemIds = {40008}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45139, enchantId = 0, gemIds = {40008}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45295, enchantId = 50965, gemIds = {40008}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45988, enchantId = 47901, gemIds = {40008}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45471, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45247, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45313, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45442, enchantId = 59619, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45587, enchantId = 62202, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45137, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Warrior Protection - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41387, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40679, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34389, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 37728, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40689, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 43500, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44201, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 34213, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37784, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37220, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 36993, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37401, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40701, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T9_BISTOOLTIP",
                name = "T9 Warrior Protection - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48433, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47133, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48455, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47549, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46968, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48453, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47076, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48447, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47003, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47157, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 45471, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47506, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 45587, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T10_BISTOOLTIP",
                name = "T10 Warrior Protection - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51221, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 50660, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51220, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51222, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51223, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50625, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50738, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50729, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_RS_BISTOOLTIP",
                name = "RS Warrior Protection - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51221, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 50660, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51220, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51222, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51223, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54579, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50738, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50729, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_PRE",
                name = "Warrior Protection - WOTLK_PRE",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T7",
                name = "Warrior Protection - WOTLK_T7",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T8",
                name = "Warrior Protection - WOTLK_T8",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T9",
                name = "Warrior Protection - WOTLK_T9",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Wrynn's Greathelm of Triumph (H)", "NECK: The Arbiter's Muse (H)", "SHOULDER: Wrynn's Pauldrons of Triumph (H)", "BACK: Magni's Resolution (H)", "CHEST: Chestplate of the Towering Monstrosity (H)", "WRIST: Bracers of the Shieldmaiden (H)", "HANDS: Wrynn's Handguards of Triumph (H)", "WAIST: Girdle of Bloodied Scars (H)", "LEGS: Wrynn's Legguards of Triumph (H)", "FEET: Dawnbreaker Greaves (H)", "RING1: Signet of the Traitor King (H)", "TRINKET1: Satrina's Impeding Scarab (H)", "MAINHAND: Silverwing Defender (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T10",
                name = "Warrior Protection - WOTLK_T10",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_PROTECTION_WOTLK_T10_PROGRESS",
                name = "Warrior Protection - WotLK T10 Progression",
                class = "WARRIOR",
                spec = "Protection",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
