-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Rogue/Subtlety/Builds.lua"] = {
    {
                id = "ROGUE_SUBTLETY_CLASSIC_PRE",
                name = "Rogue Subtlety - CLASSIC_PRE",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_CLASSIC_T1",
                name = "Rogue Subtlety - CLASSIC_T1",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_CLASSIC_T2",
                name = "Rogue Subtlety - CLASSIC_T2",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_CLASSIC_T25",
                name = "Rogue Subtlety - CLASSIC_T25",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_CLASSIC_T3",
                name = "Rogue Subtlety - CLASSIC_T3",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_TBC_PRE",
                name = "Rogue Subtlety - TBC_PRE",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                conflicts = {"RELIC: Veteran's Musket"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_TBC_T4",
                name = "Rogue Subtlety - TBC_T4",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_TBC_T5",
                name = "Rogue Subtlety - TBC_T5",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_TBC_T6_LOONBIS",
                name = "T6 Rogue Subtlety - LoonBiS TBC",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 35452, gemIds = {}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31030, enchantId = 35417, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31028, enchantId = 27960, gemIds = {}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32324, enchantId = 34002, gemIds = {}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31026, enchantId = 25080, gemIds = {}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 31029, enchantId = 35490, gemIds = {}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32366, enchantId = 34007, gemIds = {}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29301, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 30450, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32837, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32838, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29949, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Closest available LoonBiS guide used (Rogue DPS).",
            },
    {
                id = "ROGUE_SUBTLETY_TBC_T6",
                name = "Rogue Subtlety - TBC_T6",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_TBC_T6_SWP",
                name = "Rogue Subtlety - TBC Sunwell (BiS)",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_PRE_LOONBIS",
                name = "PRE Rogue Subtlety - LoonBiS WotLK",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42550, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42645, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37139, enchantId = 61117, gemIds = {40112}, notes = "", source = "loonbis" },
                    BACK = { itemId = 38614, enchantId = 55777, gemIds = {40112}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39558, enchantId = 60692, gemIds = {40112}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44203, enchantId = 57683, gemIds = {40112}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40615, enchantId = 54999, gemIds = {40112}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {40112}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37644, enchantId = 50967, gemIds = {40112}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44297, enchantId = 55016, gemIds = {40112}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 37642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40586, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37667, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37191, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T7_LOONBIS",
                name = "T7 Rogue Subtlety - LoonBiS WotLK",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40499, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40502, enchantId = 61117, gemIds = {40112}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55777, gemIds = {40112}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40539, enchantId = 60692, gemIds = {40112}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40186, enchantId = 57683, gemIds = {40112}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40630, enchantId = 54999, gemIds = {40112}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40205, enchantId = 0, gemIds = {40112}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 44011, enchantId = 50967, gemIds = {40112}, notes = "", source = "loonbis" },
                    FEET = { itemId = 39701, enchantId = 55016, gemIds = {40112}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40474, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40074, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40386, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40385, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T8_LOONBIS",
                name = "T8 Rogue Subtlety - LoonBiS WotLK",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46125, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45945, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 45245, enchantId = 61117, gemIds = {40112}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45461, enchantId = 55777, gemIds = {40112}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45473, enchantId = 60692, gemIds = {40112}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45611, enchantId = 57683, gemIds = {40112}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46124, enchantId = 54999, gemIds = {40112}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 46095, enchantId = 0, gemIds = {40112}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45536, enchantId = 50967, gemIds = {40112}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45564, enchantId = 55016, gemIds = {40112}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 46048, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45607, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45484, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45296, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_PRE",
                name = "Rogue Subtlety - WOTLK_PRE",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T7",
                name = "Rogue Subtlety - WOTLK_T7",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"WAIST: Belt of the Merciless Killer (H)"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T8",
                name = "Rogue Subtlety - WOTLK_T8",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T9",
                name = "Rogue Subtlety - WOTLK_T9",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: VanCleef's' Helmet of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: VanCleef's' Pauldrons of Triumph (H)", "BACK: Vereesa's Dexterity (H)", "CHEST: VanCleef's' Breastplate of Triumph (H)", "WRIST: Bracers of Dark Determination (H)", "HANDS: VanCleef's' Gauntlets of Triumph (H)", "WAIST: Belt of the Merciless Killer (H)", "LEGS: Leggings of the Broken Beast (H)", "FEET: Treads of the Icewalker (H)", "RING1: Planestalker Signet (H)", "RING2: Ring of Callous Aggression (H)", "TRINKET1: Death's Verdict (H)", "MAINHAND: Stormpike Cleaver (H)", "OFFHAND: Lionhead Slasher (H)", "RELIC: BRK-1000 (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T10",
                name = "Rogue Subtlety - WOTLK_T10",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_SUBTLETY_WOTLK_T10_PROGRESS",
                name = "Rogue Subtlety - WotLK T10 Progression",
                class = "ROGUE",
                spec = "Subtlety",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

