-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Rogue/Combat/Builds.lua"] = {
    {
                id = "ROGUE_COMBAT_TBC_T6_LOONBIS",
                name = "T6 Rogue Combat - LoonBiS TBC",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 35452, gemIds = {32409}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31030, enchantId = 35417, gemIds = {24055}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {24055}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31028, enchantId = 27960, gemIds = {24055}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32324, enchantId = 34002, gemIds = {24055}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31026, enchantId = 25080, gemIds = {24055}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24055}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 31029, enchantId = 35490, gemIds = {24055}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32366, enchantId = 34007, gemIds = {24055}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29301, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 30450, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32837, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32838, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29949, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
    {
                id = "ROGUE_COMBAT_CLASSIC_PRE",
                name = "Rogue Combat - CLASSIC_PRE",
                class = "ROGUE",
                spec = "Combat",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_CLASSIC_T1",
                name = "Rogue Combat - CLASSIC_T1",
                class = "ROGUE",
                spec = "Combat",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_CLASSIC_T2",
                name = "Rogue Combat - CLASSIC_T2",
                class = "ROGUE",
                spec = "Combat",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_CLASSIC_T25",
                name = "Rogue Combat - CLASSIC_T25",
                class = "ROGUE",
                spec = "Combat",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_CLASSIC_T3",
                name = "Rogue Combat - CLASSIC_T3",
                class = "ROGUE",
                spec = "Combat",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from combat-rogue; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_TBC_PRE",
                name = "Rogue Combat - TBC_PRE",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 28224, enchantId = 0, gemIds = {24054, 32409}, notes = "", source = "wowhead" },
                    NECK = { itemId = 29381, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 27797, enchantId = 0, gemIds = {24058, 24054}, notes = "", source = "wowhead" },
                    BACK = { itemId = 24259, enchantId = 0, gemIds = {24058}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 28264, enchantId = 0, gemIds = {24058, 24058, 24058}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 29246, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 25685, enchantId = 0, gemIds = {24058, 24058}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 29247, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 27837, enchantId = 0, gemIds = {24058, 24058, 24054}, notes = "", source = "wowhead" },
                    FEET = { itemId = 25686, enchantId = 0, gemIds = {24058, 24058}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 31920, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 30834, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29383, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 28288, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 28438, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 28189, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 29151, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                conflicts = {"RELIC: Veteran's Musket"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "ROGUE_COMBAT_TBC_T4",
                name = "Rogue Combat - TBC_T4",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_TBC_T5",
                name = "Rogue Combat - TBC_T5",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_TBC_T6_WOWHEAD",
                name = "T6 Rogue Combat - Wowhead",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 0, gemIds = {32206, 32409}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31030, enchantId = 0, gemIds = {32206, 32206}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32323, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31028, enchantId = 0, gemIds = {32206, 32206, 32212}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32324, enchantId = 0, gemIds = {32206}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31026, enchantId = 0, gemIds = {32206}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {32220, 32212}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 31029, enchantId = 0, gemIds = {32206}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32366, enchantId = 0, gemIds = {32220, 32206}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29301, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 30450, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32837, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 32838, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 29949, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase 3 data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "ROGUE_COMBAT_TBC_T6",
                name = "Rogue Combat - TBC_T6",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_TBC_T6_SWP",
                name = "Rogue Combat - TBC Sunwell (BiS)",
                class = "ROGUE",
                spec = "Combat",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_PRE_LOONBIS",
                name = "PRE Rogue Combat - LoonBiS WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42550, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37139, enchantId = 61117, gemIds = {40114}, notes = "", source = "loonbis" },
                    BACK = { itemId = 38614, enchantId = 55777, gemIds = {40114}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39558, enchantId = 60692, gemIds = {40114}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44203, enchantId = 57683, gemIds = {40114}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40615, enchantId = 54999, gemIds = {40114}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {40114}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37644, enchantId = 50967, gemIds = {40114}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44297, enchantId = 55016, gemIds = {40114}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40586, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 43611, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37191, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T7_LOONBIS",
                name = "T7 Rogue Combat - LoonBiS WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40499, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40502, enchantId = 61117, gemIds = {40114}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55777, gemIds = {40114}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40539, enchantId = 60692, gemIds = {40114}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 39765, enchantId = 57683, gemIds = {40114}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40541, enchantId = 54999, gemIds = {40114}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40205, enchantId = 0, gemIds = {40114}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 44011, enchantId = 50967, gemIds = {40114}, notes = "", source = "loonbis" },
                    FEET = { itemId = 39701, enchantId = 55016, gemIds = {40114}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40474, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40383, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 39714, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40385, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T8_LOONBIS",
                name = "T8 Rogue Combat - LoonBiS WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45993, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45517, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 45245, enchantId = 61117, gemIds = {40114}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45461, enchantId = 55777, gemIds = {40114}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45473, enchantId = 60692, gemIds = {40114}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45869, enchantId = 57683, gemIds = {40114}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46043, enchantId = 54999, gemIds = {40114}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 46095, enchantId = 0, gemIds = {40114}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45536, enchantId = 50967, gemIds = {40114}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45564, enchantId = 55016, gemIds = {40114}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46048, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45132, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45484, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45296, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Rogue Combat - BiS-Tooltip WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37139, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 43566, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39558, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 34448, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39560, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37644, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 34575, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40586, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 42642, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37693, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 37856, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T9_BISTOOLTIP",
                name = "T9 Rogue Combat - BiS-Tooltip WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48230, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47060, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48228, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48232, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47155, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48231, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47112, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 46975, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47077, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47934, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47075, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47156, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47001, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T10_BISTOOLTIP",
                name = "T10 Rogue Combat - BiS-Tooltip WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51252, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51254, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50656, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50670, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50697, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50343, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50654, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_RS_BISTOOLTIP",
                name = "RS Rogue Combat - BiS-Tooltip WotLK",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51252, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51254, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50656, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50697, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50654, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_PRE",
                name = "Rogue Combat - WOTLK_PRE",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T7",
                name = "Rogue Combat - WOTLK_T7",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"WAIST: Belt of the Merciless Killer (H)"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T8",
                name = "Rogue Combat - WOTLK_T8",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T9",
                name = "Rogue Combat - WOTLK_T9",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: VanCleef's' Helmet of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: VanCleef's' Pauldrons of Triumph (H)", "BACK: Vereesa's Dexterity (H)", "CHEST: VanCleef's' Breastplate of Triumph (H)", "WRIST: Bracers of Dark Determination (H)", "HANDS: VanCleef's' Gauntlets of Triumph (H)", "WAIST: Belt of the Merciless Killer (H)", "LEGS: Leggings of the Broken Beast (H)", "FEET: Treads of the Icewalker (H)", "RING1: Planestalker Signet (H)", "RING2: Ring of Callous Aggression (H)", "TRINKET1: Death's Verdict (H)", "MAINHAND: Stormpike Cleaver (H)", "OFFHAND: Lionhead Slasher (H)", "RELIC: BRK-1000 (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T10",
                name = "Rogue Combat - WOTLK_T10",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "ROGUE_COMBAT_WOTLK_T10_PROGRESS",
                name = "Rogue Combat - WotLK T10 Progression",
                class = "ROGUE",
                spec = "Combat",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

