-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "SHAMAN_RESTORATION_CLASSIC_PRE",
                name = "Shaman Restoration - CLASSIC_PRE",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_CLASSIC_T1",
                name = "Shaman Restoration - CLASSIC_T1",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_CLASSIC_T2",
                name = "Shaman Restoration - CLASSIC_T2",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_CLASSIC_T25",
                name = "Shaman Restoration - CLASSIC_T25",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_CLASSIC_T3",
                name = "Shaman Restoration - CLASSIC_T3",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_TBC_PRE",
                name = "Shaman Restoration - TBC_PRE",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 24264, enchantId = 0, gemIds = {24057, 35315, 24029}, notes = "", source = "wowhead" },
                    NECK = { itemId = 31691, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 21874, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    BACK = { itemId = 31329, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 21875, enchantId = 0, gemIds = {35315, 24057}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 29523, enchantId = 0, gemIds = {35315}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 29506, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 29524, enchantId = 0, gemIds = {24057, 35315}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30543, enchantId = 0, gemIds = {24029, 35315, 24057}, notes = "", source = "wowhead" },
                    FEET = { itemId = 27411, enchantId = 0, gemIds = {24029, 24057}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 27780, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29168, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 30841, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 23556, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 29267, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 27544, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                conflicts = {"RING1: Ring of Convalescence"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "SHAMAN_RESTORATION_TBC_T4",
                name = "Shaman Restoration - TBC_T4",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_TBC_T5",
                name = "Shaman Restoration - TBC_T5",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_TBC_T6_LOONBIS",
                name = "T6 Shaman Restoration - LoonBiS TBC",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31012, enchantId = 35445, gemIds = {}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32370, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31022, enchantId = 35404, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32524, enchantId = 34006, gemIds = {}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31016, enchantId = 27960, gemIds = {}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32577, enchantId = 27911, gemIds = {}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32328, enchantId = 33999, gemIds = {}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 32258, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 31019, enchantId = 31370, gemIds = {}, notes = "", source = "loonbis" },
                    FEET = { itemId = 30873, enchantId = 34008, gemIds = {}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32528, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32528, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32496, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32500, enchantId = 34010, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30882, enchantId = 27945, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 28523, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "SHAMAN_RESTORATION_TBC_T6",
                name = "Shaman Restoration - TBC_T6",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_TBC_T6_SWP",
                name = "Shaman Restoration - TBC Sunwell (BiS)",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_PRE_LOONBIS",
                name = "PRE Shaman Restoration - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42555, enchantId = 50368, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40681, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 34390, enchantId = 61120, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41610, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39588, enchantId = 44509, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37788, enchantId = 55628, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40614, enchantId = 55641, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40693, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37791, enchantId = 41604, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 43469, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40585, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37694, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40685, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37169, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40700, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40709, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T7_LOONBIS",
                name = "T7 Shaman Restoration - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40510, enchantId = 50368, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44662, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40513, enchantId = 61120, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40508, enchantId = 44509, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40209, enchantId = 55628, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40564, enchantId = 55641, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40272, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40512, enchantId = 41604, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 39734, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40375, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40401, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40709, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T8_LOONBIS",
                name = "T8 Shaman Restoration - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46201, enchantId = 50368, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45443, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46204, enchantId = 61120, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45486, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46198, enchantId = 44509, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45460, enchantId = 55628, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 55641, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45616, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46202, enchantId = 41604, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45537, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45614, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45535, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45466, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46017, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45470, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45114, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Shaman Restoration - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 34332, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40681, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37673, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39588, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 34438, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39591, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40693, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37791, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 34565, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37657, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37169, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40700, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40709, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T9_BISTOOLTIP",
                name = "T9 Shaman Restoration - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46201, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47144, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 46204, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47552, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46198, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 45460, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 46199, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 46991, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47190, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47099, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47224, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 45614, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45535, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47665, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T10_BISTOOLTIP",
                name = "T10 Shaman Restoration - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51247, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51245, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51249, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50687, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50703, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51246, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50464, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_RS_BISTOOLTIP",
                name = "RS Shaman Restoration - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51247, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51245, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51249, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54584, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 54560, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 54587, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51246, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50464, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_PRE",
                name = "Shaman Restoration - WOTLK_PRE",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T7",
                name = "Shaman Restoration - WOTLK_T7",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T8",
                name = "Shaman Restoration - WOTLK_T8",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T9",
                name = "Shaman Restoration - WOTLK_T9",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"NECK: Wail of the Val'kyr (H)", "BACK: Jaina's Radiance (H)", "WAIST: Belt of the Ice Burrower (H)", "LEGS: Legwraps of the Awakening (H)", "FEET: Boots of Tremoring Earth (H)", "RING1: Ring of the Darkmender (H)", "TRINKET1: Solace of the Defeated (H)", "OFFHAND: Bastion of Purity (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T10",
                name = "Shaman Restoration - WOTLK_T10",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_RESTORATION_WOTLK_T10_PROGRESS",
                name = "Shaman Restoration - WotLK T10 Progression",
                class = "SHAMAN",
                spec = "Restoration",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
