-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Warrior/Fury/Builds.lua"] = {
    {
                id = "WARRIOR_FURY_CLASSIC_PRE",
                name = "Warrior Fury - CLASSIC_PRE",
                class = "WARRIOR",
                spec = "Fury",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_CLASSIC_T1",
                name = "Warrior Fury - CLASSIC_T1",
                class = "WARRIOR",
                spec = "Fury",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_CLASSIC_T2",
                name = "Warrior Fury - CLASSIC_T2",
                class = "WARRIOR",
                spec = "Fury",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_CLASSIC_T25",
                name = "Warrior Fury - CLASSIC_T25",
                class = "WARRIOR",
                spec = "Fury",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_CLASSIC_T3",
                name = "Warrior Fury - CLASSIC_T3",
                class = "WARRIOR",
                spec = "Fury",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from fury-warrior; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_TBC_PRE",
                name = "Warrior Fury - TBC_PRE",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 32087, enchantId = 0, gemIds = {24058, 32409}, notes = "", source = "wowhead" },
                    NECK = { itemId = 29349, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 33173, enchantId = 0, gemIds = {24058, 24058}, notes = "", source = "wowhead" },
                    BACK = { itemId = 24259, enchantId = 0, gemIds = {24058}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 23522, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 23537, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 25685, enchantId = 0, gemIds = {24058, 24058}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 27985, enchantId = 0, gemIds = {24058, 24054}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30538, enchantId = 0, gemIds = {24058, 24058, 24054}, notes = "", source = "wowhead" },
                    FEET = { itemId = 25686, enchantId = 0, gemIds = {24058, 24058}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 29379, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 30834, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29383, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 28288, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
    
            {
                name = "T6 Warrior Fury - LoonBiS TBC",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 35452, gemIds = {32409}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 30979, enchantId = 29483, gemIds = {24048}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {24048}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30975, enchantId = 27960, gemIds = {24048}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 30863, enchantId = 27899, gemIds = {24048}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32278, enchantId = 33995, gemIds = {24048}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24048}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 32341, enchantId = 35490, gemIds = {24048}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32345, enchantId = 34007, gemIds = {24048}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32335, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32837, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32838, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32326, enchantId = 30252, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "WARRIOR_FURY_TBC_T4",
                name = "Warrior Fury - TBC_T4",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_TBC_T5",
                name = "Warrior Fury - TBC_T5",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_TBC_T6_LOONBIS",
                name = "T6 Warrior Fury - LoonBiS TBC",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 35452, gemIds = {}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 30979, enchantId = 29483, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30975, enchantId = 27960, gemIds = {}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 30863, enchantId = 27899, gemIds = {}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32278, enchantId = 33995, gemIds = {}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 32341, enchantId = 35490, gemIds = {}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32345, enchantId = 34007, gemIds = {}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32335, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32837, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32838, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32326, enchantId = 30252, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "WARRIOR_FURY_TBC_T6",
                name = "Warrior Fury - TBC_T6",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_TBC_T6_SWP",
                name = "Warrior Fury - TBC Sunwell (BiS)",
                class = "WARRIOR",
                spec = "Fury",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_WOTLK_PRE_LOONBIS",
                name = "PRE Warrior Fury - LoonBiS WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41386, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42645, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 44195, enchantId = 50335, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 37647, enchantId = 55002, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39606, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 41355, enchantId = 57683, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39609, enchantId = 54999, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40694, enchantId = 54793, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37193, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44306, enchantId = 55016, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 37642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37852, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37191, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T7_LOONBIS",
                name = "T7 Warrior Fury - LoonBiS WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40528, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40530, enchantId = 50335, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55002, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40539, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 39765, enchantId = 57683, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40541, enchantId = 54999, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40205, enchantId = 54793, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40318, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40591, enchantId = 55016, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40717, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 43993, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40256, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40384, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40385, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T8_LOONBIS",
                name = "T8 Warrior Fury - LoonBiS WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46151, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45459, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46149, enchantId = 50335, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 46032, enchantId = 55002, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46146, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45611, enchantId = 57683, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46148, enchantId = 54999, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 46095, enchantId = 54793, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45536, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45599, enchantId = 55016, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46322, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45516, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45296, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Warrior Fury - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41386, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34388, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 37647, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39606, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 44203, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 34180, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44306, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40586, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37642, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37852, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 37852, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T9_BISTOOLTIP",
                name = "T9 Warrior Fury - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48383, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47060, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48381, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48385, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 46967, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 47240, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47002, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48382, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47077, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47075, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 46966, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47078, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47078, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T10_BISTOOLTIP",
                name = "T10 Warrior Fury - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51227, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51229, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51225, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50670, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51228, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50639, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50343, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 49623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50730, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_RS_BISTOOLTIP",
                name = "RS Warrior Fury - BiS-Tooltip WotLK",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51227, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 54581, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51229, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51225, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51228, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54578, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 49623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50730, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARRIOR_FURY_WOTLK_PRE",
                name = "Warrior Fury - WOTLK_PRE",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T7",
                name = "Warrior Fury - WOTLK_T7",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T8",
                name = "Warrior Fury - WOTLK_T8",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T9",
                name = "Warrior Fury - WOTLK_T9",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Wrynn's Helmet of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: Wrynn's Shoulderplates of Triumph (H)", "BACK: Vereesa's Dexterity (H)", "CHEST: Wrynn's Battleplate of Triumph (H)", "WRIST: Boneshatter Armplates (H)", "HANDS: Gloves of Bitte Reprisal (H)", "WAIST: Bloodbath Belt (H)", "LEGS: Wrynn's Legplates of Triumph (H)", "FEET: Treads of the Icewalker (H)", "RING1: Ring of Callous Aggression (H)", "RING2: Band of the Violent Temperment (H)", "TRINKET2: Death's Verdict (H)", "MAINHAND: Justicebringer (H)", "OFFHAND: Justicebringer (H)", "RELIC: Talonstrike (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T10",
                name = "Warrior Fury - WOTLK_T10",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "WARRIOR_FURY_WOTLK_T10_PROGRESS",
                name = "Warrior Fury - WotLK T10 Progression",
                class = "WARRIOR",
                spec = "Fury",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

