-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "HUNTER_MARKSMANSHIP_CLASSIC_PRE",
                name = "Hunter Marksmanship - CLASSIC_PRE",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from marksmanship-hunter; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_CLASSIC_T1",
                name = "Hunter Marksmanship - CLASSIC_T1",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from marksmanship-hunter; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_CLASSIC_T2",
                name = "Hunter Marksmanship - CLASSIC_T2",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from marksmanship-hunter; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_CLASSIC_T25",
                name = "Hunter Marksmanship - CLASSIC_T25",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from marksmanship-hunter; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_CLASSIC_T3",
                name = "Hunter Marksmanship - CLASSIC_T3",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from marksmanship-hunter; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_TBC_PRE",
                name = "Hunter Marksmanship - TBC_PRE",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_TBC_T4",
                name = "Hunter Marksmanship - TBC_T4",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_TBC_T5",
                name = "Hunter Marksmanship - TBC_T5",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_TBC_T6_LOONBIS",
                name = "T6 Hunter Marksmanship - LoonBiS TBC",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 0, gemIds = {32409, 31868}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32591, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31006, enchantId = 0, gemIds = {31868, 24055}, notes = "", source = "wowhead" },
                    BACK = { itemId = 29994, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31004, enchantId = 0, gemIds = {24028, 31868, 31868}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32324, enchantId = 0, gemIds = {31868}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31001, enchantId = 0, gemIds = {24028}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30879, enchantId = 0, gemIds = {24028, 31868}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 31005, enchantId = 0, gemIds = {24028}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32366, enchantId = 0, gemIds = {24028, 31868}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29301, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 30901, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 30906, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_TBC_T6",
                name = "Hunter Marksmanship - TBC_T6",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_TBC_T6_SWP",
                name = "Hunter Marksmanship - TBC Sunwell (BiS)",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_PRE_LOONBIS",
                name = "PRE Hunter Marksmanship - LoonBiS WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42551, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42645, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37373, enchantId = 50335, gemIds = {42143}, notes = "", source = "loonbis" },
                    BACK = { itemId = 43566, enchantId = 55002, gemIds = {42143}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39579, enchantId = 60692, gemIds = {42143}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37170, enchantId = 57683, gemIds = {42143}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40614, enchantId = 44529, gemIds = {42143}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 37407, enchantId = 0, gemIds = {42143}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37669, enchantId = 50967, gemIds = {42143}, notes = "", source = "loonbis" },
                    FEET = { itemId = 37167, enchantId = 55016, gemIds = {42143}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 42642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37685, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37235, enchantId = 60707, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37191, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T7_LOONBIS",
                name = "T7 Hunter Marksmanship - LoonBiS WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40543, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40507, enchantId = 50335, gemIds = {42143}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55002, gemIds = {42143}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 43998, enchantId = 60692, gemIds = {42143}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40282, enchantId = 57683, gemIds = {42143}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40541, enchantId = 44529, gemIds = {42143}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40275, enchantId = 0, gemIds = {42143}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40506, enchantId = 50967, gemIds = {42143}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40549, enchantId = 55016, gemIds = {42143}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40074, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40474, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 39714, enchantId = 60707, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40385, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T8_LOONBIS",
                name = "T8 Hunter Marksmanship - LoonBiS WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45610, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45517, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 45300, enchantId = 50335, gemIds = {42143}, notes = "", source = "loonbis" },
                    BACK = { itemId = 46032, enchantId = 55002, gemIds = {42143}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45473, enchantId = 60692, gemIds = {42143}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45454, enchantId = 57683, gemIds = {42143}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45444, enchantId = 44529, gemIds = {42143}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45467, enchantId = 0, gemIds = {42143}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45536, enchantId = 50967, gemIds = {42143}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45562, enchantId = 55016, gemIds = {42143}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46322, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 46038, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46036, enchantId = 60707, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45570, enchantId = 41167, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Hunter Marksmanship - BiS-Tooltip WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37679, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 43406, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39579, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 43131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40692, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37669, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40586, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 42642, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 44249, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40491, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 37191, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T9_BISTOOLTIP",
                name = "T9 Hunter Marksmanship - BiS-Tooltip WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48262, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47060, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48260, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48264, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47074, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48263, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47153, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47191, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 53127, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45608, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47075, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47239, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47113, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47521, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T10_BISTOOLTIP",
                name = "T10 Hunter Marksmanship - BiS-Tooltip WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51286, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51288, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51289, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50655, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51285, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50688, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50645, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50343, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50735, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50672, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50733, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_RS_BISTOOLTIP",
                name = "RS Hunter Marksmanship - BiS-Tooltip WotLK",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51286, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51288, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51289, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51285, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50688, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50645, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54577, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50735, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50672, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50733, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_PRE",
                name = "Hunter Marksmanship - WOTLK_PRE",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T7",
                name = "Hunter Marksmanship - WOTLK_T7",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T8",
                name = "Hunter Marksmanship - WOTLK_T8",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T9",
                name = "Hunter Marksmanship - WOTLK_T9",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Windrunner's (A) Headpiece of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: Windrunner's (A) Spaulders of Triumph (H)", "BACK: Vereesa's Dexterity (H)", "CHEST: Windrunner's (A) Tunic of Triumph (H)", "WRIST: Bracers of the Untold Massacre (H)", "HANDS: Windrunner's (A) Handguards of Triumph (H)", "WAIST: Belt of Deathly Dominion (H)", "LEGS: Legguards of the Lurking Threat (H)", "RING2: Ring of Callous Aggression (H)", "TRINKET1: Death's Verdict (H)", "MAINHAND: Archon Glaive (H)", "RELIC: BRK-1000 (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T10",
                name = "Hunter Marksmanship - WOTLK_T10",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "HUNTER_MARKSMANSHIP_WOTLK_T10_PROGRESS",
                name = "Hunter Marksmanship - WotLK T10 Progression",
                class = "HUNTER",
                spec = "Marksmanship",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
