-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Priest/Holy/Builds.lua"] = {
    {
                id = "PRIEST_HOLY_TBC_T6_LOONBIS",
                name = "T6 Priest Holy - Wowhead TBC",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31063, enchantId = 35445, gemIds = {25901}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32370, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31069, enchantId = 35404, gemIds = {32836}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32524, enchantId = 25084, gemIds = {32836}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31066, enchantId = 33990, gemIds = {32836}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32584, enchantId = 27911, gemIds = {32836}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31060, enchantId = 33999, gemIds = {32836}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30895, enchantId = 0, gemIds = {32836}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30912, enchantId = 31370, gemIds = {32836}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32609, enchantId = 34008, gemIds = {32836}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32528, enchantId = 27926, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 28823, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32500, enchantId = 34010, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30911, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32363, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
    {
                id = "PRIEST_HOLY_CLASSIC_PRE",
                name = "Priest Holy - CLASSIC_PRE",
                class = "PRIEST",
                spec = "Holy",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Songstone of Ironforge"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_CLASSIC_T1",
                name = "Priest Holy - CLASSIC_T1",
                class = "PRIEST",
                spec = "Holy",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_CLASSIC_T2",
                name = "Priest Holy - CLASSIC_T2",
                class = "PRIEST",
                spec = "Holy",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_CLASSIC_T25",
                name = "Priest Holy - CLASSIC_T25",
                class = "PRIEST",
                spec = "Holy",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_CLASSIC_T3",
                name = "Priest Holy - CLASSIC_T3",
                class = "PRIEST",
                spec = "Holy",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_TBC_PRE",
                name = "Priest Holy - TBC_PRE",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 32090, enchantId = 0, gemIds = {32836, 25901}, notes = "", source = "wowhead" },
                    NECK = { itemId = 30377, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    BACK = { itemId = 29354, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 21875, enchantId = 0, gemIds = {24060, 32836}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 29183, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 27536, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 21873, enchantId = 0, gemIds = {24060, 32836}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 24261, enchantId = 0, gemIds = {32836, 24060, 24029}, notes = "", source = "wowhead" },
                    FEET = { itemId = 29251, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 29373, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29168, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 21625, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 23556, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 27885, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                conflicts = {"RING2: Ring of Convalescence"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PRIEST_HOLY_TBC_T4",
                name = "Priest Holy - TBC_T4",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_TBC_T5",
                name = "Priest Holy - TBC_T5",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_TBC_T6_WOWHEAD",
                name = "T6 Priest Holy - Wowhead TBC",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31063, enchantId = 0, gemIds = {25901, 32216}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32370, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31069, enchantId = 0, gemIds = {35489, 35489}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32524, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31066, enchantId = 0, gemIds = {35489, 32219, 35489}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32584, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31060, enchantId = 0, gemIds = {35489, 35489}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30895, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30912, enchantId = 0, gemIds = {35489, 35489, 35489}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32609, enchantId = 0, gemIds = {32219, 32216}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32528, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29309, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 28823, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32500, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 30911, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 32363, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase 3 data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PRIEST_HOLY_TBC_T6",
                name = "Priest Holy - TBC_T6",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_TBC_T6_SWP",
                name = "Priest Holy - TBC Sunwell (BiS)",
                class = "PRIEST",
                spec = "Holy",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_WOTLK_PRE_LOONBIS",
                name = "PRE Priest Holy - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42553, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 24116, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37196, enchantId = 50336, gemIds = {42148}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41609, enchantId = 63765, gemIds = {42148}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 42102, enchantId = 60692, gemIds = {42148}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 44555, gemIds = {42148}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 42113, enchantId = 54999, gemIds = {42148}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40697, enchantId = 41611, gemIds = {42148}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37189, enchantId = 41604, gemIds = {42148}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44202, enchantId = 55016, gemIds = {42148}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 44283, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37694, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37360, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 44210, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37619, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T7_LOONBIS",
                name = "T7 Priest Holy - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40562, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 24116, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40555, enchantId = 50336, gemIds = {42148}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 63765, gemIds = {42148}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 44002, enchantId = 60692, gemIds = {42148}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 44555, gemIds = {42148}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40454, enchantId = 54999, gemIds = {42148}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 41611, gemIds = {42148}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40398, enchantId = 41604, gemIds = {42148}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {42148}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 39766, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 39426, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T8_LOONBIS",
                name = "T8 Priest Holy - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45443, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46068, enchantId = 50336, gemIds = {42148}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45618, enchantId = 63765, gemIds = {42148}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46193, enchantId = 60692, gemIds = {42148}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45446, enchantId = 44555, gemIds = {42148}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 54999, gemIds = {42148}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45619, enchantId = 41611, gemIds = {42148}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46195, enchantId = 41604, gemIds = {42148}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45135, enchantId = 55016, gemIds = {42148}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45614, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 46051, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45535, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46017, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45271, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45511, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Priest Holy - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37294, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40681, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37655, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 42102, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 42113, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40697, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37854, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 44283, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37360, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 44210, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T9_BISTOOLTIP",
                name = "T9 Priest Holy - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48035, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48029, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47553, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46993, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47208, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48037, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 46973, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48033, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47097, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45495, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47224, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 46051, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47146, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T10_BISTOOLTIP",
                name = "T10 Priest Holy - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51261, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51264, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50668, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50717, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50686, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51260, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51262, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_RS_BISTOOLTIP",
                name = "RS Priest Holy - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51261, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51264, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50668, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50717, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51260, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51262, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_HOLY_WOTLK_PRE",
                name = "Priest Holy - WOTLK_PRE",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T7",
                name = "Priest Holy - WOTLK_T7",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T8",
                name = "Priest Holy - WOTLK_T8",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T9",
                name = "Priest Holy - WOTLK_T9",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Velen's Cowl of Triumph (H)", "SHOULDER: Velen's Shoulderpads of Triumph (H)", "BACK: Bolvar's Devotion (H)", "CHEST: Flowing Vestments of Ascent (H)", "WRIST: Armbands of the Ashen Saint (H)", "HANDS: Velen's Gloves of Triumph (H)", "WAIST: Cord of the Tenebrous Mist (H)", "LEGS: Velen's Leggings of Triumph (H)", "FEET: Boots of the Mourning Widow (H)", "RING2: Ring of the Darkmender (H)", "TRINKET1: Solace of the Defeated (H)", "OFFHAND: Chalice of Searing Light (H)", "RELIC: Rod of Imprisoned Souls (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T10",
                name = "Priest Holy - WOTLK_T10",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_HOLY_WOTLK_T10_PROGRESS",
                name = "Priest Holy - WotLK T10 Progression",
                class = "PRIEST",
                spec = "Holy",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

