-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Paladin/Retribution/Builds.lua"] = {
    {
                id = "PALADIN_RETRIBUTION_TBC_T6_LOONBIS",
                name = "T6 Paladin Retribution - LoonBiS TBC",
                class = "PALADIN",
                spec = "Retribution",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 35452, gemIds = {32409}, notes = "", source = "loonbis" },
                    NECK = { itemId = 30022, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 30055, enchantId = 35417, gemIds = {24054}, notes = "", source = "loonbis" },
                    BACK = { itemId = 33122, enchantId = 34004, gemIds = {24054}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30905, enchantId = 27960, gemIds = {24054}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32574, enchantId = 27899, gemIds = {24054}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 29947, enchantId = 33995, gemIds = {24054}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24054}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30900, enchantId = 35490, gemIds = {24054}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32366, enchantId = 27951, gemIds = {24054}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 30834, enchantId = 27927, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32526, enchantId = 27927, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 28830, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 29383, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32332, enchantId = 27984, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 27484, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_CLASSIC_PRE",
                name = "Paladin Retribution - CLASSIC_PRE",
                class = "PALADIN",
                spec = "Retribution",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_CLASSIC_T1",
                name = "Paladin Retribution - CLASSIC_T1",
                class = "PALADIN",
                spec = "Retribution",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_CLASSIC_T2",
                name = "Paladin Retribution - CLASSIC_T2",
                class = "PALADIN",
                spec = "Retribution",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_CLASSIC_T25",
                name = "Paladin Retribution - CLASSIC_T25",
                class = "PALADIN",
                spec = "Retribution",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_CLASSIC_T3",
                name = "Paladin Retribution - CLASSIC_T3",
                class = "PALADIN",
                spec = "Retribution",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_TBC_PRE",
                name = "Paladin Retribution - TBC_PRE",
                class = "PALADIN",
                spec = "Retribution",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_TBC_T4",
                name = "Paladin Retribution - TBC_T4",
                class = "PALADIN",
                spec = "Retribution",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_TBC_T5",
                name = "Paladin Retribution - TBC_T5",
                class = "PALADIN",
                spec = "Retribution",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_TBC_T6",
                name = "T6 Paladin Retribution - Wowhead TBC",
                class = "PALADIN",
                spec = "Retribution",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 29192, gemIds = {32409, 24058}, notes = "", source = "wowhead" },
                    NECK = { itemId = 30022, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 30055, enchantId = 28888, gemIds = {24027}, notes = "", source = "wowhead" },
                    BACK = { itemId = 33122, enchantId = 34004, gemIds = {24054}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 30905, enchantId = 27960, gemIds = {24054, 24027, 24058}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32574, enchantId = 27899, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 29947, enchantId = 33995, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24027, 24054}, notes = "", source =  "wowhead" },
                    LEGS = { itemId = 30900, enchantId = 29535, gemIds = {24027, 24058, 24054}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32366, enchantId = 27951, gemIds ={24027, 24058}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 30834, enchantId = 27927, gemIds = {}, notes = "", source ="wowhead" },
                    RING2 = { itemId = 32526, enchantId =27927, gemIds= {}, notes ="Use 'Band of the Ranger-General' instead for +HR", source ="wowhead" },
                    TRINKET1 ={ itemId=29383, enchantId=0, gemIds={}, notes="", source="wowhead" },
                    TRINKET2 ={ itemId=28830, enchantId=0, gemIds={}, notes="", source="wowhead" },
                    MAINHAND ={ itemId=32332, enchantId=27984, gemIds={}, notes="", source="wowhead" },
                    RELIC ={ itemId=27484, enchantId=0, gemIds={}, notes="", source="wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't6' sourced from wowhead.com; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_TBC_T6_SWP",
                name = "Paladin Retribution - TBC Sunwell (BiS)",
                class = "PALADIN",
                spec = "Retribution",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_PRE_LOONBIS",
                name = "PRE Paladin Retribution - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41386, enchantId = 0, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 43481, enchantId = 61117, gemIds = {42142}, notes = "", source = "loonbis" },
                    BACK = { itemId = 37647, enchantId = 55002, gemIds = {42142}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39633, enchantId = 60692, gemIds = {42142}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 41355, enchantId = 57683, gemIds = {42142}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39634, enchantId = 54999, gemIds = {42142}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40692, enchantId = 0, gemIds = {42142}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37193, enchantId = 50967, gemIds = {42142}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44297, enchantId = 55016, gemIds = {42142}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 37685, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 44935, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37852, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37574, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T7_LOONBIS",
                name = "T7 Paladin Retribution - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 44006, enchantId = 0, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40578, enchantId = 61117, gemIds = {42142}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55002, gemIds = {42142}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40574, enchantId = 60692, gemIds = {42142}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40330, enchantId = 57683, gemIds = {42142}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40541, enchantId = 54999, gemIds = {42142}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40278, enchantId = 0, gemIds = {42142}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 44011, enchantId = 50967, gemIds = {42142}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40591, enchantId = 55016, gemIds = {42142}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40474, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40717, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40431, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40384, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 42852, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T8_LOONBIS",
                name = "T8 Paladin Retribution - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45472, enchantId = 0, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45517, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 45245, enchantId = 61117, gemIds = {42142}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45461, enchantId = 55002, gemIds = {42142}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45473, enchantId = 60692, gemIds = {42142}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45663, enchantId = 57683, gemIds = {42142}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45444, enchantId = 54999, gemIds = {42142}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 46095, enchantId = 0, gemIds = {42142}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45134, enchantId = 50967, gemIds = {42142}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45599, enchantId = 55016, gemIds = {42142}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45534, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45516, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Paladin Retribution - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41386, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37139, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 37647, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 41355, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39634, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37193, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44306, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 44935, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37642, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37166, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37852, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 37574, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T9_BISTOOLTIP",
                name = "T9 Paladin Retribution - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48614, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47060, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48612, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47547, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47155, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48615, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47002, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47132, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47154, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 46966, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47075, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47519, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47661, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T10_BISTOOLTIP",
                name = "T10 Paladin Retribution - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51277, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50647, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51279, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50653, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51275, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50659, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50690, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51278, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50618, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50706, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 49623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50455, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_RS_BISTOOLTIP",
                name = "RS Paladin Retribution - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51277, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 54581, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51279, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50653, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51275, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50690, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51278, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54578, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50706, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 49623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50455, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_PRE",
                name = "Paladin Retribution - WOTLK_PRE",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T7",
                name = "Paladin Retribution - WOTLK_T7",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T8",
                name = "Paladin Retribution - WOTLK_T8",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T9",
                name = "Paladin Retribution - WOTLK_T9",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Turalyon's Helm of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: Turalyon's Shoulderplates of Triumph (H)", "BACK: Varian's Furor (H)", "CHEST: Turalyon's Battleplate of Triumph (H)", "WRIST: Bracers of Dark Determination (H)", "HANDS: Turalyon's Gauntlets of Triumph (H)", "WAIST: Bloodbath Belt (H)", "LEGS: Legguards of Ascension (H)", "FEET: Greaves of the 7th Legion (H)", "RING1: Band of the Violent Temperment (H)", "RING2: Ring of Callous Aggression (H)", "TRINKET1: Death's Verdict (H)", "MAINHAND: Catastrophe (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T10",
                name = "Paladin Retribution - WOTLK_T10",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_RETRIBUTION_WOTLK_T10_PROGRESS",
                name = "Paladin Retribution - WotLK T10 Progression",
                class = "PALADIN",
                spec = "Retribution",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Death's Verdict (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

