-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "WARLOCK_DEMONOLOGY_CLASSIC_PRE",
                name = "PRE-T1 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 18727, enchantId = 15397, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 14112, enchantId = 22599, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 11623, enchantId = 20068, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 14153, enchantId = 20088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 10461, enchantId = 20065, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 13253, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 11662, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 13170, enchantId = 15397, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 18735, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 12545, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 11824, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 12930, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 13968, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 13964, enchantId = 22753, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 11904, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 13396, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_CLASSIC_T1",
                name = "T1 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 16929, enchantId = 15397, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 18814, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 14112, enchantId = 22599, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 17078, enchantId = 20068, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 19145, enchantId = 20088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 16804, enchantId = 20065, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 13253, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 19136, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 16930, enchantId = 15397, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 18735, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 19147, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 19147, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 18820, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 12930, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 17103, enchantId = 22753, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 11904, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 13396, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_CLASSIC_T2",
                name = "T2 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 19375, enchantId = 22844, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 18814, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 19370, enchantId = 22599, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 19378, enchantId = 20068, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 19145, enchantId = 20088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 19374, enchantId = 20065, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 19407, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 16933, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 19165, enchantId = 22844, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 18735, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 19403, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 19434, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 19379, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 18820, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 19356, enchantId = 22753, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 13396, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_CLASSIC_T25",
                name = "T2.5 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 21337, enchantId = 24165, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 21608, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 21335, enchantId = 24421, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 22731, enchantId = 20068, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 19682, enchantId = 20088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 21186, enchantId = 20065, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 21585, enchantId = 25088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 22730, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 19683, enchantId = 24165, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 19684, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 21709, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 21417, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 19950, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 19379, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 21622, enchantId = 22753, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 21597, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 21603, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_CLASSIC_T3",
                name = "T3 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 22506, enchantId = 24165, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 23057, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 22507, enchantId = 29467, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 23050, enchantId = 20068, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 22504, enchantId = 20088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 21186, enchantId = 20065, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 21585, enchantId = 25088, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 22730, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 23070, enchantId = 24165, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 22508, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 21709, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 23031, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 19379, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 23206, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 22807, enchantId = 22753, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 23049, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 22820, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_TBC_PRE",
                name = "PRE-T4 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 24266, enchantId = 0, gemIds = {24056, 31867, 24030}, notes = "", source = "wowhead" },
                    NECK = { itemId = 28134, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 21869, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    BACK = { itemId = 23050, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 21871, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 21186, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 21585, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 24256, enchantId = 0, gemIds = {24030, 31867}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 24262, enchantId = 0, gemIds = {24056, 31867, 24030}, notes = "", source = "wowhead" },
                    FEET = { itemId = 21870, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 29172, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 28227, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 27683, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 31336, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 29273, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 28386, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                conflicts = {"MAINHAND: Blade of the Archmage"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "WARLOCK_DEMONOLOGY_TBC_T4",
                name = "T4 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 28963, enchantId = 35447, gemIds = {34220, 31867}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 28530, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 28967, enchantId = 35406, gemIds = {24056, 31867}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 28766, enchantId = 25084, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 28964, enchantId = 27960, gemIds = {31867, 31867, 31867}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 24250, enchantId = 27917, gemIds = {31867}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 28968, enchantId = 33997, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 24256, enchantId = 0, gemIds = {31867, 31867}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 24262, enchantId = 31372, gemIds = {31867, 31867, 31867}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 21870, enchantId = 34008, gemIds = {31867, 24056}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 28793, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 28753, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 27683, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 28802, enchantId = 27982, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 29273, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 28673, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_TBC_T5",
                name = "T5 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 30212, enchantId = 35447, gemIds = {34220, 24056}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 28967, enchantId = 35406, gemIds = {31867, 31867}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 28766, enchantId = 25084, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 30214, enchantId = 27960, gemIds = {31867, 31867, 24056}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 29918, enchantId = 27917, gemIds = {31867}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 28968, enchantId = 33997, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 30038, enchantId = 0, gemIds = {31867, 31867}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 30213, enchantId = 31372, gemIds = {24030}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 30037, enchantId = 34008, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 30109, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 29308, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 29132, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 30095, enchantId = 27982, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 30049, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_TBC_T6_LOONBIS",
                name = "T6 Warlock Demonology - LoonBiS TBC",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31051, enchantId = 35447, gemIds = {}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32349, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31054, enchantId = 35406, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32590, enchantId = 25084, gemIds = {}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30107, enchantId = 27960, gemIds = {}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31050, enchantId = 33997, gemIds = {}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30038, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30916, enchantId = 31372, gemIds = {}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32239, enchantId = 34008, gemIds = {}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32527, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32247, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 27683, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 30910, enchantId = 27982, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30872, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
    
            {
                name = "T6 Warlock Demonology - LoonBiS TBC",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31051, enchantId = 35447, gemIds = {34220}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32349, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31054, enchantId = 35406, gemIds = {24030}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32590, enchantId = 25084, gemIds = {24030}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30107, enchantId = 27960, gemIds = {24030}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {24030}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31050, enchantId = 33997, gemIds = {24030}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30038, enchantId = 0, gemIds = {24030}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30916, enchantId = 31372, gemIds = {24030}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32239, enchantId = 34008, gemIds = {24030}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32527, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32247, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 27683, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 30910, enchantId = 27982, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30872, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_TBC_T6",
                name = "T6 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31051, enchantId = 35447, gemIds = {34220, 32221}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 34204, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 31054, enchantId = 35406, gemIds = {32215}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 32331, enchantId = 25084, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 31052, enchantId = 27960, gemIds = {32196, 32196, 32196}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 31050, enchantId = 33997, gemIds = {32196}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 30038, enchantId = 0, gemIds = {32221, 32210}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 31053, enchantId = 31372, gemIds = {32196}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 30035, enchantId = 34008, gemIds = {32196, 32196}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 32374, enchantId = 27982, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_TBC_T6_SWP",
                name = "Warlock Demonology - TBC Sunwell (BiS)",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31051, enchantId = 35447, gemIds = {34220, 32221}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 34204, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 31054, enchantId = 35406, gemIds = {32215}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 32331, enchantId = 25084, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 31052, enchantId = 27960, gemIds = {32196, 32196, 32196}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 31050, enchantId = 33997, gemIds = {32196}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 30038, enchantId = 0, gemIds = {32221, 32210}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 31053, enchantId = 31372, gemIds = {32196}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 30035, enchantId = 34008, gemIds = {32196, 32196}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 32374, enchantId = 27982, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_PRE_LOONBIS",
                name = "PRE PRE-T7 Warlock Demonology - WoWTBC.GG - LoonBiS WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37684, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42032, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37196, enchantId = 61120, gemIds = {42144}, notes = "", source = "loonbis" },
                    BACK = { itemId = 42066, enchantId = 55642, gemIds = {42144}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39497, enchantId = 33990, gemIds = {42144}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 57691, gemIds = {42144}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40613, enchantId = 54999, gemIds = {42144}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 44309, enchantId = 41611, gemIds = {42144}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 34170, enchantId = 41602, gemIds = {42144}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {42144}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 44934, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 42644, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42395, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45085, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40699, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 34348, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T7_LOONBIS",
                name = "T7 PRE-T7 Warlock Demonology - WoWTBC.GG - LoonBiS WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40421, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40637, enchantId = 61120, gemIds = {42144}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40405, enchantId = 55642, gemIds = {42144}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40423, enchantId = 33990, gemIds = {42144}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 57691, gemIds = {42144}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40628, enchantId = 54999, gemIds = {42144}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 41611, gemIds = {42144}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40398, enchantId = 41602, gemIds = {42144}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {42144}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40080, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40719, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40396, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 39766, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 39426, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T8_LOONBIS",
                name = "T8 PRE-T7 Warlock Demonology - WoWTBC.GG - LoonBiS WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46068, enchantId = 61120, gemIds = {42144}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45618, enchantId = 55642, gemIds = {42144}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45240, enchantId = 33990, gemIds = {42144}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45446, enchantId = 57691, gemIds = {42144}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 54999, gemIds = {42144}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45619, enchantId = 41611, gemIds = {42144}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45488, enchantId = 41602, gemIds = {42144}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45135, enchantId = 55016, gemIds = {42144}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45148, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45620, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45294, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_PRE_BISTOOLTIP",
                name = "PRE PRE-T7 Warlock Demonology - WoWTBC.GG - BiS-Tooltip WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40680, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34210, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39497, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 42113, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 34386, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 43253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 45085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T9_BISTOOLTIP",
                name = "T9 PRE-T7 Warlock Demonology - WoWTBC.GG - BiS-Tooltip WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 47789, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 47792, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47553, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 47791, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47208, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 47788, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 46973, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47062, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47097, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45495, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46980, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47958, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T10_BISTOOLTIP",
                name = "T10 PRE-T7 Warlock Demonology - WoWTBC.GG - BiS-Tooltip WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51231, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51234, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50668, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50717, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50686, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51230, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50702, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51232, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50732, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_RS_BISTOOLTIP",
                name = "RS PRE-T7 Warlock Demonology - WoWTBC.GG - BiS-Tooltip WotLK",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51231, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51234, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50717, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51230, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50702, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51232, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50732, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_PRE",
                name = "PRE-T7 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37684, enchantId = 59970, gemIds = {41285, 40026}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 40680, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 34210, enchantId = 59937, gemIds = {39998, 40049}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 41610, enchantId = 47898, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 39497, enchantId = 60692, gemIds = {39998, 40049}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 37361, enchantId = 60767, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 42113, enchantId = 44592, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {40049, 39998}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 34386, enchantId = 55631, gemIds = {39998, 40049, 40049}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 44202, enchantId = 47901, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 43253, enchantId = 0, gemIds = {40026}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 37694, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 45085, enchantId = 60714, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 34348, enchantId = 0, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T7",
                name = "T7 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40421, enchantId = 59970, gemIds = {41285, 40049}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {40026}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 40424, enchantId = 59937, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 44005, enchantId = 47898, gemIds = {40026}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 40423, enchantId = 60692, gemIds = {39998, 40051}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 44008, enchantId = 60767, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 40420, enchantId = 44592, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 40561, enchantId = 0, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 40560, enchantId = 55631, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 40558, enchantId = 47901, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 40399, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 40719, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 40396, enchantId = 60714, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 40273, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 39426, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T8",
                name = "T8 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 59970, gemIds = {41285, 39998}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 46068, enchantId = 59937, gemIds = {39998, 39998}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 45618, enchantId = 47898, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 46137, enchantId = 60692, gemIds = {39998, 40051}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 45446, enchantId = 60767, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 45665, enchantId = 44592, gemIds = {39998, 39998}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 45619, enchantId = 0, gemIds = {39998, 39998, 39998}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 46139, enchantId = 55631, gemIds = {39998, 39998}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 45135, enchantId = 47901, gemIds = {39998, 39998}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 45297, enchantId = 0, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 45495, enchantId = 0, gemIds = {40026}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 45148, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 45620, enchantId = 60714, gemIds = {40026}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 45294, enchantId = 0, gemIds = {39998}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T9",
                name = "T9 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 47796, enchantId = 59970, gemIds = {41285, 40133}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 47793, enchantId = 59937, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 47554, enchantId = 47898, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 47794, enchantId = 60692, gemIds = {40113, 40133}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 47324, enchantId = 60767, gemIds = {40133}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 47797, enchantId = 44592, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 47258, enchantId = 0, gemIds = {40133, 40113, 40113}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 47274, enchantId = 55631, gemIds = {40113, 40133, 40133}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 47293, enchantId = 47901, gemIds = {40133, 40113}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 45495, enchantId = 0, gemIds = {40133}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 47327, enchantId = 0, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 47261, enchantId = 60714, gemIds = {40133}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 47913, enchantId = 0, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 45294, enchantId = 0, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T10",
                name = "T10 Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51208, enchantId = 59970, gemIds = {41285, 40133}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 50005, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 51205, enchantId = 59937, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 53489, enchantId = 47898, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 50172, enchantId = 60692, gemIds = {40133, 40113, 40153}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 53486, enchantId = 60767, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 51209, enchantId = 44592, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 50063, enchantId = 0, gemIds = {40153, 40113, 40113}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 51207, enchantId = 55631, gemIds = {40113, 40113}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 50062, enchantId = 47901, gemIds = {40133, 40113}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 50424, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 50360, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 50427, enchantId = 60714, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 50423, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 50472, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
            },
    {
                id = "WARLOCK_DEMONOLOGY_WOTLK_T10_PROGRESS",
                name = "T10-PRG Warlock Demonology - WoWTBC.GG",
                class = "WARLOCK",
                spec = "Demonology",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 51208, enchantId = 59970, gemIds = {41285, 40133}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 50005, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 51205, enchantId = 59937, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 50014, enchantId = 47898, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 50172, enchantId = 60692, gemIds = {40133, 40113, 40153}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 50032, enchantId = 60767, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 51209, enchantId = 44592, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 50063, enchantId = 0, gemIds = {40153, 40113, 40113}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 51207, enchantId = 55631, gemIds = {40113, 40113}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 50062, enchantId = 47901, gemIds = {40133, 40113}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 50424, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 50360, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 50427, enchantId = 60714, gemIds = {40113}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 50423, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 50472, enchantId = 0, gemIds = {40153}, notes = "", source = "wowtbc.gg" },
            },
}
