-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "PRIEST_SHADOW_TBC_T6_LOONBIS",
                name = "T6 Priest Shadow - Wowhead TBC",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31064, enchantId = 35447, gemIds = {25893}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32349, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31070, enchantId = 35406, gemIds = {28118}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32590, enchantId = 25084, gemIds = {28118}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31065, enchantId = 27960, gemIds = {28118}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {28118}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31061, enchantId = 33997, gemIds = {28118}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 32256, enchantId = 0, gemIds = {28118}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30916, enchantId = 31372, gemIds = {28118}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32239, enchantId = 34008, gemIds = {28118}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 31856, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32374, enchantId = 27982, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
    {
                id = "PRIEST_SHADOW_CLASSIC_PRE",
                name = "Priest Shadow - CLASSIC_PRE",
                class = "PRIEST",
                spec = "Shadow",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Songstone of Ironforge"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_CLASSIC_T1",
                name = "Priest Shadow - CLASSIC_T1",
                class = "PRIEST",
                spec = "Shadow",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_CLASSIC_T2",
                name = "Priest Shadow - CLASSIC_T2",
                class = "PRIEST",
                spec = "Shadow",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_CLASSIC_T25",
                name = "Priest Shadow - CLASSIC_T25",
                class = "PRIEST",
                spec = "Shadow",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_CLASSIC_T3",
                name = "Priest Shadow - CLASSIC_T3",
                class = "PRIEST",
                spec = "Shadow",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_TBC_PRE",
                name = "Priest Shadow - TBC_PRE",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 24266, enchantId = 0, gemIds = {24056, 31867, 24030}, notes = "", source = "wowhead" },
                    NECK = { itemId = 28245, enchantId = 0, gemIds = {31867}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 21869, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    BACK = { itemId = 31201, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 21871, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 31225, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31166, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 31199, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 24262, enchantId = 0, gemIds = {24056, 31867, 24030}, notes = "", source = "wowhead" },
                    FEET = { itemId = 21870, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 21709, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 23031, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 27683, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 30832, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 29272, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 25295, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PRIEST_SHADOW_TBC_T4",
                name = "Priest Shadow - TBC_T4",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_TBC_T5",
                name = "Priest Shadow - TBC_T5",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_TBC_T6_WOWHEAD",
                name = "T6 Priest Shadow - Wowhead TBC",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31064, enchantId = 0, gemIds = {25893, 32215}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32349, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31070, enchantId = 0, gemIds = {32196}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32590, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31065, enchantId = 0, gemIds = {32196}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32586, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31061, enchantId = 0, gemIds = {32196}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 32256, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30916, enchantId = 0, gemIds = {32196}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32239, enchantId = 0, gemIds = {32196}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32527, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 32528, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 31856, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32374, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase 3 data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PRIEST_SHADOW_TBC_T6",
                name = "Priest Shadow - TBC_T6",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_TBC_T6_SWP",
                name = "Priest Shadow - TBC Sunwell (BiS)",
                class = "PRIEST",
                spec = "Shadow",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_PRE_LOONBIS",
                name = "PRE Priest Shadow - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 44909, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 39472, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41610, enchantId = 55642, gemIds = {40113}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 42102, enchantId = 60692, gemIds = {40113}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 55628, gemIds = {40113}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39530, enchantId = 55641, gemIds = {40113}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40696, enchantId = 41611, gemIds = {40113}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {40113}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40585, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 42644, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 41384, enchantId = 59625, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 37238, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T7_LOONBIS",
                name = "T7 Priest Shadow - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40562, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40555, enchantId = 61120, gemIds = {40113}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 55642, gemIds = {40113}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40234, enchantId = 60692, gemIds = {40113}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 55628, gemIds = {40113}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40454, enchantId = 55641, gemIds = {40113}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 41611, gemIds = {40113}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40560, enchantId = 41602, gemIds = {40113}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {40113}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40719, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 59625, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40273, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 39712, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T8_LOONBIS",
                name = "T8 Priest Shadow - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46172, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46165, enchantId = 61120, gemIds = {40113}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45242, enchantId = 55642, gemIds = {40113}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46168, enchantId = 60692, gemIds = {40113}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45446, enchantId = 55628, gemIds = {40113}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 55641, gemIds = {40113}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45619, enchantId = 41611, gemIds = {40113}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46170, enchantId = 41602, gemIds = {40113}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45135, enchantId = 55016, gemIds = {40113}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45466, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45620, enchantId = 59625, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45294, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Priest Shadow - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 34340, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40680, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34210, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39523, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39530, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37854, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 43253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 41384, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T9_BISTOOLTIP",
                name = "T9 Priest Shadow - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47144, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48082, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47552, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48083, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47208, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 45665, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 46973, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48084, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47097, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45495, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47206, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47064, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T10_BISTOOLTIP",
                name = "T10 Priest Shadow - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51255, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51257, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51259, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50651, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51256, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_RS_BISTOOLTIP",
                name = "RS Priest Shadow - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51255, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51257, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51259, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51256, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 54588, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_PRE",
                name = "Priest Shadow - WOTLK_PRE",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T7",
                name = "Priest Shadow - WOTLK_T7",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T8",
                name = "Priest Shadow - WOTLK_T8",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T9",
                name = "Priest Shadow - WOTLK_T9",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Velen's Circlet of Triumph (H)", "NECK: Wail of the Val'kyr (H)", "SHOULDER: Velen's Mantle of Triumph (H)", "BACK: Jaina's Radiance (H)", "CHEST: Velen's Raiments of Triumph (H)", "WRIST: Armbands of the Ashen Saint (H)", "WAIST: Cord of the Tenebrous Mist (H)", "LEGS: Velen's Pants of Triumph (H)", "FEET: Boots of the Mourning Widow (H)", "RING2: Band of Deplorable Violence (H)", "TRINKET2: Reign of the Unliving (H)", "MAINHAND: Misery's End (H)", "OFFHAND: Symbol of Transgression (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T10",
                name = "Priest Shadow - WOTLK_T10",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_SHADOW_WOTLK_T10_PROGRESS",
                name = "Priest Shadow - WotLK T10 Progression",
                class = "PRIEST",
                spec = "Shadow",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
