-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Druid/Balance/Builds.lua"] = {
    {
                id = "DRUID_BALANCE_CLASSIC_PRE",
                name = "Druid Balance - CLASSIC_PRE",
                class = "DRUID",
                spec = "Balance",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Songstone of Ironforge"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_CLASSIC_T1",
                name = "Druid Balance - CLASSIC_T1",
                class = "DRUID",
                spec = "Balance",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_CLASSIC_T2",
                name = "Druid Balance - CLASSIC_T2",
                class = "DRUID",
                spec = "Balance",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_CLASSIC_T25",
                name = "Druid Balance - CLASSIC_T25",
                class = "DRUID",
                spec = "Balance",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_CLASSIC_T3",
                name = "Druid Balance - CLASSIC_T3",
                class = "DRUID",
                spec = "Balance",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_TBC_PRE",
                name = "Druid Balance - TBC_PRE",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_TBC_T4",
                name = "Druid Balance - TBC_T4",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_TBC_T5",
                name = "Druid Balance - TBC_T5",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_TBC_T6_WOWHEAD",
                name = "T6 Druid Balance - Wowhead",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    -- y = 31867, b = 24056, r = 24030
                    HEAD = { itemId = 31040, enchantId = 29191, gemIds = {34220, 31867}, notes = "", source = "wowhead" },
                    NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31049, enchantId = 28909, gemIds = {24056, 31867}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32524, enchantId = 25084, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31043, enchantId = 46502, gemIds = {24056, 24056, 31867}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32586, enchantId = 46498, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31035, enchantId = 46514, gemIds = {31867}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30888, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30916, enchantId = 24274, gemIds = {31867, 31867, 24056}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32239, enchantId = 46470, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32527, enchantId = 46518, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29305, enchantId = 46518, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 32486, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32374, enchantId = 46540, gemIds = {}, notes = "", source ="wowhead" },
                    RELIC = { itemId = 32387, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't6' sourced from Wowhead. Enchants from Wowhead gem/enchants guides.",
            },
    {
                id = "DRUID_BALANCE_TBC_T6_LOONBIS",
                name = "T6 Druid Balance - LoonBiS TBC",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31040, enchantId = 35447, gemIds = {34220}, notes = "", source = "loonbis" },
                    NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31049, enchantId = 35437, gemIds = {24056}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32524, enchantId = 25084, gemIds = {24056}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31043, enchantId = 27960, gemIds = {24056}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {24056}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31035, enchantId = 33997, gemIds = {24056}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30888, enchantId = 0, gemIds = {24056}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30916, enchantId = 31372, gemIds = {24056}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32239, enchantId = 34008, gemIds = {24056}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29305, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 32486, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 33687, enchantId = 27981, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30872, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32387, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Enchants from Wowhead gem/enchants guides.",
            },
    {
                id = "DRUID_BALANCE_TBC_T6",
                name = "Druid Balance - TBC_T6",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_TBC_T6_SWP",
                name = "Druid Balance - TBC Sunwell (BiS)",
                class = "DRUID",
                spec = "Balance",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_PRE_LOONBIS",
                name = "PRE Druid Balance - LoonBiS WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42554, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40680, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37673, enchantId = 50338, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41610, enchantId = 47898, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39547, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39544, enchantId = 44592, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40696, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37791, enchantId = 41602, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44202, enchantId = 60623, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40585, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 43253, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45085, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40712, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T7_LOONBIS",
                name = "T7 Druid Balance - LoonBiS WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40467, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40470, enchantId = 50338, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 47898, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40469, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40466, enchantId = 44592, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40560, enchantId = 41602, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40519, enchantId = 60623, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40080, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40192, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40321, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T8_LOONBIS",
                name = "T8 Druid Balance - LoonBiS WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45133, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46196, enchantId = 50338, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45242, enchantId = 47898, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45519, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45446, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 44592, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45616, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45488, enchantId = 41602, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45537, enchantId = 60623, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45466, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46017, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40321, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Druid Balance - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37180, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40680, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34210, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39547, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39544, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37791, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 43253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 41384, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40712, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T9_BISTOOLTIP",
                name = "T9 Druid Balance - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48171, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47144, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48168, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47552, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48169, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47143, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48172, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47084, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47190, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47097, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 46046, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47206, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47064, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47670, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T10_BISTOOLTIP",
                name = "T10 Druid Balance - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51290, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51292, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51294, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 51872, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50663, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50457, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_RS_BISTOOLTIP",
                name = "RS Druid Balance - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51290, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51292, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51294, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50663, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50457, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
            {
                name = "PRE Druid Balance - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 48164, enchantId = 59970, gemIds = {41285, 40153}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45933, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 48167, enchantId = 59937, gemIds = {40152}, notes = "", source = "wowhead" },
                    BACK = { itemId = 45242, enchantId = 55642, gemIds = {40153}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 48166, enchantId = 60692, gemIds = {40113, 40113}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 47585, enchantId = 60767, gemIds = {40113}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 48163, enchantId = 54999, gemIds = {40113}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 47081, enchantId = 0, gemIds = {40113, 40113}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 49891, enchantId = 55631, gemIds = {40113, 40152, 40133}, notes = "", source = "wowhead" },
                    FEET = { itemId = 49890, enchantId = 55016, gemIds = {40113, 40133}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 46046, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45495, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 47182, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 47193, enchantId = 60714, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 47138, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 47670, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 'pre' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T7_ALLIANCE_DRAENEI_IN_PARTY_WOWHEAD",
                name = "T7 Druid Balance (Alliance (Draenei In Party)) - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40467, enchantId = 59970, gemIds = {41285, 39998}, notes = "", source = "wowhead" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {40026}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 40470, enchantId = 59937, gemIds = {39998}, notes = "", source = "wowhead" },
                    BACK = { itemId = 44005, enchantId = 63765, gemIds = {40026}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 40469, enchantId = 60692, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 40325, enchantId = 60767, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 40466, enchantId = 54999, gemIds = {39998}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 40561, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 40398, enchantId = 55631, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    FEET = { itemId = 40519, enchantId = 55016, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 40399, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 40080, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 40273, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40321, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't7' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T7_HORDE_NO_DRAENEI_WOWHEAD",
                name = "T7 Druid Balance (Horde (No Draenei)) - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40467, enchantId = 59970, gemIds = {41285, 39998}, notes = "", source = "wowhead" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {40026}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 40470, enchantId = 59937, gemIds = {39998}, notes = "", source = "wowhead" },
                    BACK = { itemId = 44005, enchantId = 63765, gemIds = {40026}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 40469, enchantId = 60692, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 44008, enchantId = 60767, gemIds = {39998}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 40466, enchantId = 54999, gemIds = {39998}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 40561, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 40560, enchantId = 55631, gemIds = {}, notes = "", source = "wowhead" },
                    FEET = { itemId = 40519, enchantId = 55016, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 40399, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 40080, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 40192, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40321, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't7' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T8_ALLIANCE_WOWHEAD",
                name = "T8 Druid Balance (Alliance) - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 59970, gemIds = {41285, 45883}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45933, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 46196, enchantId = 59937, gemIds = {40026}, notes = "", source = "wowhead" },
                    BACK = { itemId = 45242, enchantId = 63765, gemIds = {40048}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 46194, enchantId = 60692, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 45446, enchantId = 60767, gemIds = {39998}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 45665, enchantId = 54999, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 45619, enchantId = 0, gemIds = {39998, 39998, 39998}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 45488, enchantId = 55631, gemIds = {39998, 39998, 39998}, notes = "", source = "wowhead" },
                    FEET = { itemId = 45537, enchantId = 55016, gemIds = {39998, 40026}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 46046, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45495, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 45466, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 45620, enchantId = 60714, gemIds = {39998}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40321, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't8' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T8_HORDE_WOWHEAD",
                name = "T8 Druid Balance (Horde) - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 59970, gemIds = {41285, 45883}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45133, enchantId = 0, gemIds = {40048}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 46196, enchantId = 59937, gemIds = {39998}, notes = "", source = "wowhead" },
                    BACK = { itemId = 45242, enchantId = 63765, gemIds = {40048}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 45519, enchantId = 60692, gemIds = {40048, 39998, 40026}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 45446, enchantId = 60767, gemIds = {39998}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 45665, enchantId = 54999, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 45619, enchantId = 0, gemIds = {39998, 39998, 39998}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 46192, enchantId = 55631, gemIds = {39998, 39998}, notes = "", source = "wowhead" },
                    FEET = { itemId = 45537, enchantId = 55016, gemIds = {39998, 40026}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 46046, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45495, enchantId = 0, gemIds = {39998}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 45466, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 45620, enchantId = 60714, gemIds = {39998}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40321, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't8' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T10_ALLIANCE_WOWHEAD",
                name = "T10 Druid Balance (Alliance) - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51290, enchantId = 59970, gemIds = {41285, 40113}, notes = "", source = "wowhead" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 51292, enchantId = 59937, gemIds = {40113}, notes = "", source = "wowhead" },
                    BACK = { itemId = 54583, enchantId = 55642, gemIds = {40155}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 51294, enchantId = 60692, gemIds = {40113, 40155}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 54582, enchantId = 60767, gemIds = {40113}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 51291, enchantId = 54999, gemIds = {40113}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {40113, 40113, 40113}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 50694, enchantId = 55631, gemIds = {40113, 40133, 40155}, notes = "", source = "wowhead" },
                    FEET = { itemId = 50699, enchantId = 55016, gemIds = {40133, 40113}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 50664, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 50398, enchantId = 0, gemIds = {40155}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 50734, enchantId = 60714, gemIds = {40113}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 50457, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't10' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T10_HORDE_WOWHEAD",
                name = "T10 Druid Balance (Horde) - Wowhead WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51290, enchantId = 59970, gemIds = {41285, 40113}, notes = "", source = "wowhead" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 51292, enchantId = 59937, gemIds = {40113}, notes = "", source = "wowhead" },
                    BACK = { itemId = 54583, enchantId = 55642, gemIds = {40113}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 51294, enchantId = 60692, gemIds = {40113, 40153}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 54582, enchantId = 60767, gemIds = {40155}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 51291, enchantId = 54999, gemIds = {40113}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {40113, 40113, 40113}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 50694, enchantId = 55631, gemIds = {40113, 40133, 40153}, notes = "", source = "wowhead" },
                    FEET = { itemId = 50699, enchantId = 55016, gemIds = {40133, 40113}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 50664, enchantId = 0, gemIds = {40113}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 50398, enchantId = 0, gemIds = {40153}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 50734, enchantId = 60714, gemIds = {40113}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 50457, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't10' sourced from Wowhead gear planner.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_RS_BISTOOLTIP",
                name = "RS Druid Balance - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51290, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50724, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51292, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51294, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50663, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50457, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_BALANCE_WOTLK_PRE",
                name = "Druid Balance - WOTLK_PRE",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T7",
                name = "Druid Balance - WOTLK_T7",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T8",
                name = "Druid Balance - WOTLK_T8",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T9",
                name = "Druid Balance - WOTLK_T9",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Malfurion's Cover of Triumph (H)", "NECK: Wail of the Val'kyr (H)", "SHOULDER: Malfurion's Mantle of Triumph (H)", "BACK: Jaina's Radiance (H)", "CHEST: Malfurion's Vestments of Triumph (H)", "WRIST: Bindings of Dark Essence (H)", "HANDS: Malfurion's Gloves of Triumph (H)", "WAIST: Cord of Biting Cold (H)", "LEGS: Legwraps of the Awakening (H)", "FEET: Boots of the Mourning Widow (H)", "RING1: Band of Deplorable Violence (H)", "TRINKET1: Reign of the Unliving (H)", "MAINHAND: Misery's End (H)", "OFFHAND: Symbol of Transgression (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T10",
                name = "Druid Balance - WOTLK_T10",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_BALANCE_WOTLK_T10_PROGRESS",
                name = "Druid Balance - WotLK T10 Progression",
                class = "DRUID",
                spec = "Balance",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

