-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "MAGE_ARCANE_CLASSIC_PRE",
                name = "Mage Arcane - CLASSIC_PRE",
                class = "MAGE",
                spec = "Arcane",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Songstone of Ironforge"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_CLASSIC_T1",
                name = "Mage Arcane - CLASSIC_T1",
                class = "MAGE",
                spec = "Arcane",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_CLASSIC_T2",
                name = "Mage Arcane - CLASSIC_T2",
                class = "MAGE",
                spec = "Arcane",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_CLASSIC_T25",
                name = "Mage Arcane - CLASSIC_T25",
                class = "MAGE",
                spec = "Arcane",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_CLASSIC_T3",
                name = "Mage Arcane - CLASSIC_T3",
                class = "MAGE",
                spec = "Arcane",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_TBC_PRE",
                name = "Mage Arcane - TBC_PRE",
                class = "MAGE",
                spec = "Arcane",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                conflicts = {"MAINHAND: Blade of the Archmage"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_TBC_T4",
                name = "Mage Arcane - TBC_T4",
                class = "MAGE",
                spec = "Arcane",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_TBC_T5",
                name = "Mage Arcane - TBC_T5",
                class = "MAGE",
                spec = "Arcane",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_TBC_T6_LOONBIS",
                name = "T6 Mage Arcane - LoonBiS TBC",
                class = "MAGE",
                spec = "Arcane",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 30206, enchantId = 0, gemIds = {34220, 31867}, notes = "", source = "wowhead" },
                    NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 30210, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32331, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 30196, enchantId = 0, gemIds = {31867, 31867, 24056}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 30870, enchantId = 0, gemIds = {31867}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 30205, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30888, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 31058, enchantId = 0, gemIds = {24056}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32239, enchantId = 0, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 29305, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 32527, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 30720, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32374, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 30872, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 28783, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon).",
            },
    {
                id = "MAGE_ARCANE_TBC_T6",
                name = "Mage Arcane - TBC_T6",
                class = "MAGE",
                spec = "Arcane",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_TBC_T6_SWP",
                name = "Mage Arcane - TBC Sunwell (BiS)",
                class = "MAGE",
                spec = "Arcane",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_WOTLK_PRE_LOONBIS",
                name = "PRE Mage Arcane - LoonBiS WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42553, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 39472, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 34210, enchantId = 50338, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41610, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39492, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39495, enchantId = 54999, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40696, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 34181, enchantId = 56039, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44202, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40585, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37694, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37360, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40699, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 34347, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T7_LOONBIS",
                name = "T7 Mage Arcane - LoonBiS WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40416, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40419, enchantId = 50338, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40418, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39733, enchantId = 54999, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40417, enchantId = 56039, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40719, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 39229, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40396, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40273, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 39712, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T8_LOONBIS",
                name = "T8 Mage Arcane - LoonBiS WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45497, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46134, enchantId = 50338, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45618, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46130, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 54999, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45619, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45488, enchantId = 56039, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45135, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45466, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45620, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45294, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Mage Arcane - BiS-Tooltip WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37294, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40680, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34210, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39492, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39495, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 34181, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37360, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T9_BISTOOLTIP",
                name = "T9 Mage Arcane - BiS-Tooltip WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 47761, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47144, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 47758, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47553, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46993, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47208, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 47762, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 46973, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47760, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47097, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 45495, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46980, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47958, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T10_BISTOOLTIP",
                name = "T10 Mage Arcane - BiS-Tooltip WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51281, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51284, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51283, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50686, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50722, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51282, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50732, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_RS_BISTOOLTIP",
                name = "RS Mage Arcane - BiS-Tooltip WotLK",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51281, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51284, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51283, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50722, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51282, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 54588, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50732, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50719, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "MAGE_ARCANE_WOTLK_PRE",
                name = "Mage Arcane - WOTLK_PRE",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T7",
                name = "Mage Arcane - WOTLK_T7",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T8",
                name = "Mage Arcane - WOTLK_T8",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T9",
                name = "Mage Arcane - WOTLK_T9",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Khadgar's Hood of Triumph (H)", "NECK: Wail of the Val'kyr (H)", "SHOULDER: Khadgar's Shoulderpads of Triumph (H)", "BACK: Bolvar's Devotion (H)", "CHEST: Flowing Vestments of Ascent (H)", "WRIST: Armbands of the Ashen Saint (H)", "HANDS: Khadgar's Gauntlets of Triumph (H)", "WAIST: Cord of the Tenebrous Mist (H)", "LEGS: Khadgar's Leggings of Triumph (H)", "FEET: Boots of the Mourning Widow (H)", "RING1: Band of Deplorable Violence (H)", "TRINKET1: Reign of the Unliving (H)", "MAINHAND: Blade of Tarasque (H)", "OFFHAND: Chalice of Benedictus (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T10",
                name = "Mage Arcane - WOTLK_T10",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "MAGE_ARCANE_WOTLK_T10_PROGRESS",
                name = "Mage Arcane - WotLK T10 Progression",
                class = "MAGE",
                spec = "Arcane",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Reign of the Unliving (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
