-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Priest/Discipline/Builds.lua"] = {
    {
                id = "PRIEST_DISCIPLINE_CLASSIC_PRE",
                name = "Priest Discipline - CLASSIC_PRE",
                class = "PRIEST",
                spec = "Discipline",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Songstone of Ironforge"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_CLASSIC_T1",
                name = "Priest Discipline - CLASSIC_T1",
                class = "PRIEST",
                spec = "Discipline",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_CLASSIC_T2",
                name = "Priest Discipline - CLASSIC_T2",
                class = "PRIEST",
                spec = "Discipline",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_CLASSIC_T25",
                name = "Priest Discipline - CLASSIC_T25",
                class = "PRIEST",
                spec = "Discipline",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_CLASSIC_T3",
                name = "Priest Discipline - CLASSIC_T3",
                class = "PRIEST",
                spec = "Discipline",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from shadow-priest; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_TBC_PRE",
                name = "Priest Discipline - TBC_PRE",
                class = "PRIEST",
                spec = "Discipline",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                conflicts = {"RING2: Ring of Convalescence"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_TBC_T4",
                name = "Priest Discipline - TBC_T4",
                class = "PRIEST",
                spec = "Discipline",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_TBC_T5",
                name = "Priest Discipline - TBC_T5",
                class = "PRIEST",
                spec = "Discipline",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_TBC_T6_LOONBIS",
                name = "T6 Priest Discipline - LoonBiS TBC",
                class = "PRIEST",
                spec = "Discipline",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31063, enchantId = 35445, gemIds = {}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32370, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31069, enchantId = 35404, gemIds = {}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32524, enchantId = 25084, gemIds = {}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31066, enchantId = 33990, gemIds = {}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32584, enchantId = 27911, gemIds = {}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31060, enchantId = 33999, gemIds = {}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30895, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30912, enchantId = 31370, gemIds = {}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32609, enchantId = 34008, gemIds = {}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32528, enchantId = 27926, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32528, enchantId = 27926, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 28823, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32500, enchantId = 34010, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30911, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32363, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Closest available LoonBiS guide used (Holy).",
            },
    {
                id = "PRIEST_DISCIPLINE_TBC_T6",
                name = "Priest Discipline - TBC_T6",
                class = "PRIEST",
                spec = "Discipline",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_TBC_T6_SWP",
                name = "Priest Discipline - TBC Sunwell (BiS)",
                class = "PRIEST",
                spec = "Discipline",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_PRE_LOONBIS",
                name = "PRE Priest Discipline - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42553, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 24116, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37196, enchantId = 50336, gemIds = {42144}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41609, enchantId = 63765, gemIds = {42144}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39515, enchantId = 60692, gemIds = {42144}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 60767, gemIds = {42144}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39519, enchantId = 44592, gemIds = {42144}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40696, enchantId = 41611, gemIds = {42144}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37622, enchantId = 41604, gemIds = {42144}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44202, enchantId = 55016, gemIds = {42144}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 42644, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 44283, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42132, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37835, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37169, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 44210, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 34348, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T7_LOONBIS",
                name = "T7 Priest Discipline - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40562, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 24116, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40555, enchantId = 50336, gemIds = {42144}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 63765, gemIds = {42144}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40194, enchantId = 60692, gemIds = {42144}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 60767, gemIds = {42144}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40303, enchantId = 44592, gemIds = {42144}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 41611, gemIds = {42144}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40398, enchantId = 41604, gemIds = {42144}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40269, enchantId = 55016, gemIds = {42144}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 44255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 39766, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40245, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T8_LOONBIS",
                name = "T8 Priest Discipline - LoonBiS WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46197, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45443, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46190, enchantId = 50336, gemIds = {42144}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45486, enchantId = 63765, gemIds = {42144}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46193, enchantId = 60692, gemIds = {42144}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45446, enchantId = 60767, gemIds = {42144}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45520, enchantId = 44592, gemIds = {42144}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45619, enchantId = 41611, gemIds = {42144}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46195, enchantId = 41604, gemIds = {42144}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45537, enchantId = 55016, gemIds = {42144}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45614, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45946, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45535, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46017, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45617, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45294, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Priest Discipline - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37294, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40681, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37196, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39515, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39519, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40697, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37854, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 44283, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 42644, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 42988, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40685, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37169, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 44210, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T9_BISTOOLTIP",
                name = "T9 Priest Discipline - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46197, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47930, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 46190, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47238, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46193, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47587, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 46188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 45619, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47189, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 46050, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47733, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47146, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T10_BISTOOLTIP",
                name = "T10 Priest Discipline - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51261, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50700, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51264, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50468, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51263, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50686, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51260, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50702, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51823, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 51850, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50720, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47146, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_RS_BISTOOLTIP",
                name = "RS Priest Discipline - BiS-Tooltip WotLK",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51261, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50700, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51264, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51263, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50686, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51260, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50702, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51823, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 51850, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50720, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47146, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_PRE",
                name = "Priest Discipline - WOTLK_PRE",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T7",
                name = "Priest Discipline - WOTLK_T7",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T8",
                name = "Priest Discipline - WOTLK_T8",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T9",
                name = "Priest Discipline - WOTLK_T9",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"NECK: Amulet of Binding Elements (H)", "BACK: Maiden's Favor (H)", "LEGS: Leggings of the Deepening Void (H)", "RING1: Band of Deplorable Violence (H)", "TRINKET1: Solace of the Defeated (H)", "OFFHAND: Chalice of Searing Light (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T10",
                name = "Priest Discipline - WOTLK_T10",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)", "OFFHAND: Chalice of Searing Light (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PRIEST_DISCIPLINE_WOTLK_T10_PROGRESS",
                name = "Priest Discipline - WotLK T10 Progression",
                class = "PRIEST",
                spec = "Discipline",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)", "OFFHAND: Chalice of Searing Light (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

