-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Paladin/Protection/Builds.lua"] = {
    {
                id = "PALADIN_PROTECTION_TBC_T6_LOONBIS",
                name = "T6 Paladin Protection - Wowhead TBC",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32521, enchantId = 35447, gemIds = {25896}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32362, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 30998, enchantId = 35402, gemIds = {32200}, notes = "", source = "loonbis" },
                    BACK = { itemId = 34010, enchantId = 25086, gemIds = {32200}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30991, enchantId = 27960, gemIds = {32200}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32279, enchantId = 27914, gemIds = {32200}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 30985, enchantId = 25072, gemIds = {32200}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 32342, enchantId = 0, gemIds = {32200}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30995, enchantId = 35495, gemIds = {32200}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32245, enchantId = 27950, gemIds = {32200}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 30083, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29172, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 31858, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 32501, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 30910, enchantId = 27975, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 32375, enchantId = 34009, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29388, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
    {
                id = "PALADIN_PROTECTION_CLASSIC_PRE",
                name = "Paladin Protection - CLASSIC_PRE",
                class = "PALADIN",
                spec = "Protection",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_CLASSIC_T1",
                name = "Paladin Protection - CLASSIC_T1",
                class = "PALADIN",
                spec = "Protection",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_CLASSIC_T2",
                name = "Paladin Protection - CLASSIC_T2",
                class = "PALADIN",
                spec = "Protection",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_CLASSIC_T25",
                name = "Paladin Protection - CLASSIC_T25",
                class = "PALADIN",
                spec = "Protection",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_CLASSIC_T3",
                name = "Paladin Protection - CLASSIC_T3",
                class = "PALADIN",
                spec = "Protection",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Classic data sourced from retribution-paladin; used as closest available spec. Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_TBC_PRE",
                name = "Paladin Protection - TBC_PRE",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 32083, enchantId = 0, gemIds = {24033, 25896}, notes = "", source = "wowhead" },
                    NECK = { itemId = 28245, enchantId = 0, gemIds = {31867}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 27706, enchantId = 0, gemIds = {24030, 31867}, notes = "", source = "wowhead" },
                    BACK = { itemId = 27804, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 28203, enchantId = 0, gemIds = {24030, 31867, 24033}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 29252, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 30741, enchantId = 0, gemIds = {31867, 24033}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 29253, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 29184, enchantId = 0, gemIds = {24030, 31867, 24033}, notes = "", source = "wowhead" },
                    FEET = { itemId = 29254, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 28407, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29172, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 27529, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 23836, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32450, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 29176, enchantId = 0, gemIds = {24033, 24033}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 29388, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PALADIN_PROTECTION_TBC_T4",
                name = "Paladin Protection - TBC_T4",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_TBC_T5",
                name = "Paladin Protection - TBC_T5",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_TBC_T6_WOWHEAD",
                name = "T6 Paladin Protection - Wowhead TBC",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32521, enchantId = 0, gemIds = {25896, 32196}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32362, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 30998, enchantId = 0, gemIds = {32200, 32196}, notes = "", source = "wowhead" },
                    BACK = { itemId = 34010, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 30991, enchantId = 0, gemIds = {32196, 32196, 32221}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32279, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 30985, enchantId = 0, gemIds = {32196}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 32342, enchantId = 0, gemIds = {32200, 32200}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30995, enchantId = 0, gemIds = {32200}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32245, enchantId = 0, gemIds = {32200, 32200}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 30083, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 32261, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 31858, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 31859, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 30910, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 32375, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 29388, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase 3 data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "PALADIN_PROTECTION_TBC_T6",
                name = "Paladin Protection - TBC_T6",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_TBC_T6_SWP",
                name = "Paladin Protection - TBC Sunwell (BiS)",
                class = "PALADIN",
                spec = "Protection",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_PRE_LOONBIS",
                name = "PRE Paladin Protection - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41387, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40679, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40675, enchantId = 44957, gemIds = {36767}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39638, enchantId = 47900, gemIds = {36767}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 44183, enchantId = 63770, gemIds = {36767}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40689, enchantId = 0, gemIds = {36767}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 43500, enchantId = 50965, gemIds = {36767}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44243, enchantId = 44528, gemIds = {36767}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 42643, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40707, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T7_LOONBIS",
                name = "T7 Paladin Protection - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40581, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44665, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40584, enchantId = 44957, gemIds = {36767}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40722, enchantId = 44591, gemIds = {36767}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 44000, enchantId = 47900, gemIds = {36767}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40306, enchantId = 57690, gemIds = {36767}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40580, enchantId = 63770, gemIds = {36767}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 39759, enchantId = 0, gemIds = {36767}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40589, enchantId = 50965, gemIds = {36767}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40297, enchantId = 44528, gemIds = {36767}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40707, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T8_LOONBIS",
                name = "T8 Paladin Protection - LoonBiS WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45502, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45485, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40637, enchantId = 44957, gemIds = {36767}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45496, enchantId = 44591, gemIds = {36767}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46173, enchantId = 47900, gemIds = {36767}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45111, enchantId = 57690, gemIds = {36767}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45487, enchantId = 63770, gemIds = {36767}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 39759, enchantId = 0, gemIds = {36767}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45594, enchantId = 50965, gemIds = {36767}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45471, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40718, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46097, enchantId = 64579, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45587, enchantId = 62202, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45145, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Paladin Protection - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41387, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40679, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 44188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39638, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39639, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40689, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 43500, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44201, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 42643, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37784, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37220, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 36993, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37401, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 43085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T9_BISTOOLTIP",
                name = "T9 Paladin Protection - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48644, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47133, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48646, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47549, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46968, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48643, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47076, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48645, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47003, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45471, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47157, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47156, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 46964, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47661, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T10_BISTOOLTIP",
                name = "T10 Paladin Protection - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51266, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 50660, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51265, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51267, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51268, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50625, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50672, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50729, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47661, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_RS_BISTOOLTIP",
                name = "RS Paladin Protection - BiS-Tooltip WotLK",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51266, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 50660, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51265, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51267, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51268, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54579, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50672, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50729, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47661, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_PRE",
                name = "Paladin Protection - WOTLK_PRE",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T7",
                name = "Paladin Protection - WOTLK_T7",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T8",
                name = "Paladin Protection - WOTLK_T8",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T9",
                name = "Paladin Protection - WOTLK_T9",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Turalyon's Faceguard of Triumph (H)", "NECK: The Arbiter's Muse (H)", "SHOULDER: Turalyon's Shoulderguards of Triumph (H)", "BACK: Magni's Resolution (H)", "CHEST: Chestplate of the Towering Monstrosity (H)", "WRIST: Bracers of the Shieldmaiden (H)", "HANDS: Turalyon's Handguards of Triumph (H)", "WAIST: Girdle of Bloodied Scars (H)", "LEGS: Turalyon's Legguards of Triumph (H)", "FEET: Dawnbreaker Greaves (H)", "RING2: Signet of the Traitor King (H)", "TRINKET1: Satrina's Impeding Scarab (H)", "MAINHAND: Stormpike Cleaver (H)", "OFFHAND: Crystal Plated Vanguard (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T10",
                name = "Paladin Protection - WOTLK_T10",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "PALADIN_PROTECTION_WOTLK_T10_PROGRESS",
                name = "Paladin Protection - WotLK T10 Progression",
                class = "PALADIN",
                spec = "Protection",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}

