-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "SHAMAN_ENHANCEMENT_CLASSIC_PRE",
                name = "Shaman Enhancement - CLASSIC_PRE",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_CLASSIC_T1",
                name = "Shaman Enhancement - CLASSIC_T1",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_CLASSIC_T2",
                name = "Shaman Enhancement - CLASSIC_T2",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_CLASSIC_T25",
                name = "Shaman Enhancement - CLASSIC_T25",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_CLASSIC_T3",
                name = "Shaman Enhancement - CLASSIC_T3",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_PRE",
                name = "Shaman Enhancement - TBC_PRE",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 28224, enchantId = 0, gemIds = {24054, 32409}, notes = "", source = "wowhead" },
                    NECK = { itemId = 29381, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 27797, enchantId = 0, gemIds = {24027, 24054}, notes = "", source = "wowhead" },
                    BACK = { itemId = 24259, enchantId = 0, gemIds = {24027}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 29525, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 29527, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 25685, enchantId = 0, gemIds = {24058, 24027}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 29526, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 31544, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    FEET = { itemId = 25686, enchantId = 0, gemIds = {24058, 24027}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 30834, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 31920, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 29383, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 28288, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 28313, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 27815, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Pre-raid data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_T4",
                name = "Shaman Enhancement - TBC_T4",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_T5",
                name = "Shaman Enhancement - TBC_T5",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_T6_WOWHEAD",
                name = "T6 Shaman Enhancement - Wowhead TBC",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 0, gemIds = {32409, 32217}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 32581, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32323, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 30905, enchantId = 0, gemIds = {32193, 32211, 32217}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 30863, enchantId = 0, gemIds = {32193}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 32234, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30900, enchantId = 0, gemIds = {32193, 32217, 32211}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32366, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32497, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29301, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 29383, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 33669, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 32262, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 27815, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase 3 data sourced from wowhead.com; item IDs and gem sockets parsed from local Wowhead HTML.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_T6",
                name = "Shaman Enhancement - TBC_T6",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_T6_SWP",
                name = "Shaman Enhancement - TBC Sunwell (BiS)",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_PRE_LOONBIS",
                name = "PRE Shaman Enhancement - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42551, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37373, enchantId = 61117, gemIds = {39999}, notes = "", source = "loonbis" },
                    BACK = { itemId = 43566, enchantId = 55777, gemIds = {39999}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39597, enchantId = 60692, gemIds = {39999}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 43131, enchantId = 55628, gemIds = {39999}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39601, enchantId = 55641, gemIds = {39999}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 37407, enchantId = 41611, gemIds = {39999}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37644, enchantId = 50967, gemIds = {39999}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44297, enchantId = 55016, gemIds = {39999}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 37642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40586, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37390, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45085, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40704, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40708, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T7_LOONBIS",
                name = "T7 Shaman Enhancement - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40543, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40524, enchantId = 61117, gemIds = {39999}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55777, gemIds = {39999}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40523, enchantId = 60692, gemIds = {39999}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40736, enchantId = 55628, gemIds = {39999}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40520, enchantId = 55641, gemIds = {39999}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 39762, enchantId = 41611, gemIds = {39999}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40522, enchantId = 50967, gemIds = {39999}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40549, enchantId = 55016, gemIds = {39999}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40474, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40074, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 39763, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 39468, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40322, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T8_LOONBIS",
                name = "T8 Shaman Enhancement - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45610, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45517, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46203, enchantId = 61117, gemIds = {39999}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45461, enchantId = 55777, gemIds = {39999}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46205, enchantId = 60692, gemIds = {39999}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45460, enchantId = 55628, gemIds = {39999}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46199, enchantId = 55641, gemIds = {39999}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45553, enchantId = 41611, gemIds = {39999}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45654, enchantId = 50967, gemIds = {39999}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45989, enchantId = 55016, gemIds = {39999}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45456, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 46038, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45132, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 42608, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Shaman Enhancement - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37373, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39597, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 43131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39601, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37669, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 43251, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 40586, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37390, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 45085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40704, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40708, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T9_BISTOOLTIP",
                name = "T9 Shaman Enhancement - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48353, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47060, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48351, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47552, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46965, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47916, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48354, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47112, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48352, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47099, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47075, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 46046, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47206, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47156, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47666, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T10_BISTOOLTIP",
                name = "T10 Shaman Enhancement - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51242, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51240, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50689, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50687, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51243, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51241, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50711, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50604, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50458, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_RS_BISTOOLTIP",
                name = "RS Shaman Enhancement - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51242, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51240, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50689, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54584, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51243, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 54587, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51241, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50711, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50737, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50458, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_PRE",
                name = "Shaman Enhancement - WOTLK_PRE",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T7",
                name = "Shaman Enhancement - WOTLK_T7",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T8",
                name = "Shaman Enhancement - WOTLK_T8",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T9",
                name = "Shaman Enhancement - WOTLK_T9",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Nobundo's Faceguard of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: Nobundo's Shoulderguards of Triumph (H)", "BACK: Jaina's Radiance (H)", "CHEST: Breastplate of Cruel Intent (H)", "WRIST: Armbands of the Northern Stalker (H)", "HANDS: Nobundo's Grips of Triumph (H)", "WAIST: Belt of the Merciless Killer (H)", "LEGS: Nobundo's War-Kilt of Triumph (H)", "FEET: Boots of Tremoring Earth (H)", "RING1: Ring of Callous Aggression (H)", "TRINKET1: Reign of the Unliving (H)", "MAINHAND: Misery's End (H)", "OFFHAND: Stormpike Cleaver (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T10",
                name = "Shaman Enhancement - WOTLK_T10",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_WOTLK_T10_PROGRESS",
                name = "Shaman Enhancement - WotLK T10 Progression",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ENHANCEMENT_TBC_T6_LOONBIS",
                name = "T6 Shaman Enhancement - Wowhead TBC",
                class = "SHAMAN",
                spec = "Enhancement",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 32235, enchantId = 35452, gemIds = {32409}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 32581, enchantId = 35417, gemIds = {24054}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {24054}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 30905, enchantId = 27960, gemIds = {24054}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 30863, enchantId = 27899, gemIds = {24054}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32234, enchantId = 33995, gemIds = {24054}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24054}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30900, enchantId = 35490, gemIds = {24054}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32366, enchantId = 34007, gemIds = {24054}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32497, enchantId = 27927, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29301, enchantId = 27927, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 29383, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 33669, enchantId = 42974, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 27815, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
}
