-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_PRE_LOONBIS",
                name = "PRE Deathknight Blood (DPS) - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41387, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40679, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 44312, enchantId = 44957, gemIds = {40119}, notes = "", source = "loonbis" },
                    BACK = { itemId = 43565, enchantId = 47672, gemIds = {40119}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39623, enchantId = 47900, gemIds = {40119}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37620, enchantId = 62256, gemIds = {40119}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39624, enchantId = 50963, gemIds = {40119}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40689, enchantId = 0, gemIds = {40119}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 43500, enchantId = 50965, gemIds = {40119}, notes = "", source = "loonbis" },
                    FEET = { itemId = 41392, enchantId = 47901, gemIds = {40119}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 42643, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40718, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 42341, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37401, enchantId = 53344, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40714, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon). Closest available LoonBiS guide used (Blood Tank).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T7_LOONBIS",
                name = "T7 Deathknight Blood (DPS) - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40565, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40387, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40568, enchantId = 44957, gemIds = {40119}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40252, enchantId = 47672, gemIds = {40119}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40559, enchantId = 47900, gemIds = {40119}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40306, enchantId = 62256, gemIds = {40119}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40563, enchantId = 50963, gemIds = {40119}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 39759, enchantId = 0, gemIds = {40119}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40589, enchantId = 50965, gemIds = {40119}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40297, enchantId = 47901, gemIds = {40119}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40718, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40370, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 42341, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40402, enchantId = 53344, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40714, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon). Closest available LoonBiS guide used (Blood Tank).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T8_LOONBIS",
                name = "T8 Deathknight Blood (DPS) - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46120, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45485, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46122, enchantId = 44957, gemIds = {40119}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45496, enchantId = 47672, gemIds = {40119}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46118, enchantId = 47900, gemIds = {40119}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45111, enchantId = 62256, gemIds = {40119}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46119, enchantId = 50963, gemIds = {40119}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45551, enchantId = 0, gemIds = {40119}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45594, enchantId = 50965, gemIds = {40119}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45988, enchantId = 47901, gemIds = {40119}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45471, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45871, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 46021, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45442, enchantId = 53344, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45144, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon). Closest available LoonBiS guide used (Blood Tank).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T10_BISTOOLTIP",
                name = "T10 Deathknight Blood (DPS) - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51312, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50728, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51314, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50677, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51310, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50659, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51313, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50639, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 52572, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50693, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 49623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50459, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_RS_BISTOOLTIP",
                name = "RS Deathknight Blood (DPS) - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51312, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 54581, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51314, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50677, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51310, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51313, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54578, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 52572, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 49623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50459, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_PRE",
                name = "Deathknight Blood (DPS) - WOTLK_PRE",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T7",
                name = "Deathknight Blood (DPS) - WOTLK_T7",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T8",
                name = "Deathknight Blood (DPS) - WOTLK_T8",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T9",
                name = "Deathknight Blood (DPS) - WOTLK_T9",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T10",
                name = "Deathknight Blood (DPS) - WOTLK_T10",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_DPS_WOTLK_T10_PROGRESS",
                name = "Deathknight Blood (DPS) - WotLK T10 Progression",
                class = "DEATHKNIGHT",
                spec = "Blood (DPS)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Death's Verdict (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_PRE_LOONBIS",
                name = "PRE Deathknight Blood (Tank) - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41387, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40679, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 44312, enchantId = 44957, gemIds = {40119}, notes = "", source = "loonbis" },
                    BACK = { itemId = 43565, enchantId = 47672, gemIds = {40119}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39623, enchantId = 47900, gemIds = {40119}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37620, enchantId = 62256, gemIds = {40119}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39624, enchantId = 50963, gemIds = {40119}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40689, enchantId = 0, gemIds = {40119}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 43500, enchantId = 50965, gemIds = {40119}, notes = "", source = "loonbis" },
                    FEET = { itemId = 41392, enchantId = 47901, gemIds = {40119}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 42643, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40718, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 42341, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37401, enchantId = 53344, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40714, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_PRE_WOWHEAD",
                name = "PRE Deathknight Blood (Tank) - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 50855, enchantId = 67839, gemIds = {41380, 40130}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45485, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 50853, enchantId = 62384, gemIds = {40119}, notes = "", source = "wowhead" },
                    BACK = { itemId = 45496, enchantId = 47672, gemIds = {40119}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 50968, enchantId = 47900, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 47570, enchantId = 57690, gemIds = {40119}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 50978, enchantId = 63770, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 50991, enchantId = 0, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 49904, enchantId = 60583, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    FEET = { itemId = 49907, enchantId = 55016, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 45471, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 47731, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 47080, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 50356, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 46067, enchantId = 62158, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 50462, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Imported from Wowhead gear planner (Phase 6). User requested WotLK PRE label.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T7_WOWHEAD",
                name = "T7 Deathknight Blood (Tank) - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40565, enchantId = 67839, gemIds = {41380, 40008}, notes = "", source = "wowhead" },
                    NECK = { itemId = 40387, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 40568, enchantId = 62384, gemIds = {40022}, notes = "", source = "wowhead" },
                    BACK = { itemId = 40252, enchantId = 47672, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 40559, enchantId = 47900, gemIds = {40008, 40008}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 40306, enchantId = 62256, gemIds = {40008}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 40563, enchantId = 63770, gemIds = {40008}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 39759, enchantId = 54793, gemIds = {40008}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 40589, enchantId = 60581, gemIds = {}, notes = "", source = "wowhead" },
                    FEET = { itemId = 40297, enchantId = 47901, gemIds = {}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 40107, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 40718, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 37220, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 44063, enchantId = 0, gemIds = {40008, 40008}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 40402, enchantId = 70164, gemIds = {}, notes = "", source = "wowhead" },
                    OFFHAND = { itemId = 40402, enchantId = 70164, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 40822, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't7' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T8_WOWHEAD",
                name = "T8 Deathknight Blood (Tank) - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46120, enchantId = 67839, gemIds = {41380, 36767}, notes = "", source = "wowhead" },
                    NECK = { itemId = 45485, enchantId = 0, gemIds = {40008}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 46122, enchantId = 62384, gemIds = {40008}, notes = "", source = "wowhead" },
                    BACK = { itemId = 45496, enchantId = 47672, gemIds = {40022}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 46118, enchantId = 47900, gemIds = {36767, 36767}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 45111, enchantId = 62256, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 46119, enchantId = 63770, gemIds = {40008}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 45551, enchantId = 54736, gemIds = {40008, 40008, 40008}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 45594, enchantId = 60581, gemIds = {40008, 40008, 40008}, notes = "", source = "wowhead" },
                    FEET = { itemId = 45988, enchantId = 55016, gemIds = {40008, 40008}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 45471, enchantId = 0, gemIds = {40008}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 45871, enchantId = 0, gemIds = {45880}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 46021, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 45533, enchantId = 62158, gemIds = {40008, 40008}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 45144, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't8' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T9_REALISTIC_WOWHEAD",
                name = "T9 Deathknight Blood (Tank) (Realistic) - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 49467, enchantId = 67839, gemIds = {41380, 40119}, notes = "", source = "wowhead" },
                    NECK = { itemId = 47133, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 47698, enchantId = 62384, gemIds = {40119}, notes = "", source = "wowhead" },
                    BACK = { itemId = 47549, enchantId = 47672, gemIds = {40119}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 46968, enchantId = 47900, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 47111, enchantId = 62256, gemIds = {40119}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 45487, enchantId = 63770, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 47076, enchantId = 0, gemIds = {40130, 36767, 36767}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 47061, enchantId = 60583, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    FEET = { itemId = 47003, enchantId = 55016, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 49489, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 47955, enchantId = 0, gemIds = {36767}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 47515, enchantId = 62158, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 47672, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't9' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T9_TIER_WOWHEAD",
                name = "T9 Deathknight Blood (Tank) (Tier) - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48545, enchantId = 67839, gemIds = {41380, 40119}, notes = "", source = "wowhead" },
                    NECK = { itemId = 47133, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 48543, enchantId = 62384, gemIds = {40119}, notes = "", source = "wowhead" },
                    BACK = { itemId = 47549, enchantId = 47672, gemIds = {40119}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 46968, enchantId = 47900, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 47111, enchantId = 62256, gemIds = {40119}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 48546, enchantId = 63770, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 47076, enchantId = 0, gemIds = {40130, 36767, 36767}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 47061, enchantId = 60583, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    FEET = { itemId = 47003, enchantId = 55016, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 49489, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 47955, enchantId = 0, gemIds = {36767}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 47515, enchantId = 62158, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 47672, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't9' sourced from Wowhead gear planner.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T10_WOWHEAD",
                name = "T10 Deathknight Blood (Tank) - Wowhead WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 50640, enchantId = 67839, gemIds = {41380, 40130}, notes = "", source = "wowhead" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 51309, enchantId = 62384, gemIds = {40119}, notes = "", source = "wowhead" },
                    BACK = { itemId = 50718, enchantId = 47672, gemIds = {40119}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 51305, enchantId = 47900, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 51901, enchantId = 57690, gemIds = {40119}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 51307, enchantId = 63770, gemIds = {40119}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 51308, enchantId = 60583, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    FEET = { itemId = 54579, enchantId = 55016, gemIds = {40119, 40119}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 50404, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 50622, enchantId = 0, gemIds = {40119}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 50344, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 50735, enchantId = 62158, gemIds = {40119, 40119, 40119}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 50462, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't10' sourced from Wowhead gear planner.",
            },
    {
               id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T7_LOONBIS",
               name = "T7 Deathknight Blood (Tank) - LoonBiS WotLK",
               class = "DEATHKNIGHT",
               spec = "Blood (Tank)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40565, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40387, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40568, enchantId = 44957, gemIds = {40119}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40252, enchantId = 47672, gemIds = {40119}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40559, enchantId = 47900, gemIds = {40119}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40306, enchantId = 62256, gemIds = {40119}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40563, enchantId = 50963, gemIds = {40119}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 39759, enchantId = 0, gemIds = {40119}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40589, enchantId = 50965, gemIds = {40119}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40297, enchantId = 47901, gemIds = {40119}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40718, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40370, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 42341, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40402, enchantId = 53344, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40714, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T8_LOONBIS",
                name = "T8 Deathknight Blood (Tank) - LoonBiS WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46120, enchantId = 50369, gemIds = {41380}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45485, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46122, enchantId = 44957, gemIds = {40119}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45496, enchantId = 47672, gemIds = {40119}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46118, enchantId = 47900, gemIds = {40119}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45111, enchantId = 62256, gemIds = {40119}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46119, enchantId = 50963, gemIds = {40119}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45551, enchantId = 0, gemIds = {40119}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45594, enchantId = 50965, gemIds = {40119}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45988, enchantId = 47901, gemIds = {40119}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45471, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45871, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 46021, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45442, enchantId = 53344, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45144, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Deathknight Blood (Tank) - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 41387, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40679, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37814, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 43565, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39623, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37620, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39624, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40689, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 43500, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44201, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 42643, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37784, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37220, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 36993, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 41257, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 39344, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40822, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T9_BISTOOLTIP",
                name = "T9 Deathknight Blood (Tank) - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47133, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48543, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47549, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 46968, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 45487, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47076, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47061, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47003, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45471, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47157, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47515, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47506, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47672, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T10_BISTOOLTIP",
                name = "T10 Deathknight Blood (Tank) - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51306, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51309, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51305, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51307, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 50612, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50625, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50730, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50738, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50462, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_RS_BISTOOLTIP",
                name = "RS Deathknight Blood (Tank) - BiS-Tooltip WotLK",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 50640, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51309, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51305, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51307, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50691, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51308, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 54579, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50730, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50738, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50462, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_PRE",
                name = "Deathknight Blood (Tank) - WOTLK_PRE",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T7",
                name = "Deathknight Blood (Tank) - WOTLK_T7",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T8",
                name = "Deathknight Blood (Tank) - WOTLK_T8",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T9",
                name = "Deathknight Blood (Tank) - WOTLK_T9",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Thassarian's Faceguard of Triumph (H)", "NECK: The Arbiter's Muse (H)", "SHOULDER: Thassarian's Pauldrons of Triumph (H)", "BACK: Magni's Resolution (H)", "CHEST: Chestplate of the Towering Monstrosity (H)", "WRIST: Bracers of the Shieldmaiden (H)", "WAIST: Girdle of Bloodied Scars (H)", "LEGS: Legguards of Feverish Dedication (H)", "FEET: Dawnbreaker Greaves (H)", "RING2: Signet of the Traitor King (H)", "TRINKET1: Satrina's Impeding Scarab (H)", "MAINHAND: Decimation (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T10",
                name = "Deathknight Blood (Tank) - WOTLK_T10",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DEATHKNIGHT_BLOOD_TANK_WOTLK_T10_PROGRESS",
                name = "Deathknight Blood (Tank) - WotLK T10 Progression",
                class = "DEATHKNIGHT",
                spec = "Blood (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
