-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "DRUID_RESTORATION_CLASSIC_PRE",
                name = "Druid Restoration - CLASSIC_PRE",
                class = "DRUID",
                spec = "Restoration",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_CLASSIC_T1",
                name = "Druid Restoration - CLASSIC_T1",
                class = "DRUID",
                spec = "Restoration",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_CLASSIC_T2",
                name = "Druid Restoration - CLASSIC_T2",
                class = "DRUID",
                spec = "Restoration",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_CLASSIC_T25",
                name = "Druid Restoration - CLASSIC_T25",
                class = "DRUID",
                spec = "Restoration",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_CLASSIC_T3",
                name = "Druid Restoration - CLASSIC_T3",
                class = "DRUID",
                spec = "Restoration",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_TBC_PRE",
                name = "Druid Restoration - TBC_PRE",
                class = "DRUID",
                spec = "Restoration",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_TBC_T4",
                name = "Druid Restoration - TBC_T4",
                class = "DRUID",
                spec = "Restoration",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_TBC_T5",
                name = "Druid Restoration - TBC_T5",
                class = "DRUID",
                spec = "Restoration",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_TBC_T6_LOONBIS",
                name = "T6 Druid Restoration - LoonBiS TBC",
                class = "DRUID",
                spec = "Restoration",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31037, enchantId = 35445, gemIds = {25897}, notes = "", source = "loonbis" },
                    NECK = { itemId = 30018, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31047, enchantId = 35404, gemIds = {24029}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32524, enchantId = 25084, gemIds = {24029}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31041, enchantId = 33990, gemIds = {24029}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 30868, enchantId = 27911, gemIds = {24029}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 32328, enchantId = 33999, gemIds = {24029}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30895, enchantId = 0, gemIds = {24029}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30912, enchantId = 31370, gemIds = {24029}, notes = "", source = "loonbis" },
                    FEET = { itemId = 30737, enchantId = 34008, gemIds = {24029}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32528, enchantId = 27926, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 30110, enchantId = 27926, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 29376, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 38288, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32500, enchantId = 34010, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 30911, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 27886, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Enchants from Wowhead gem/enchants guides.",
            },
    {
                id = "DRUID_RESTORATION_TBC_T6",
                name = "Druid Restoration - TBC_T6",
                class = "DRUID",
                spec = "Restoration",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_TBC_T6_SWP",
                name = "Druid Restoration - TBC Sunwell (BiS)",
                class = "DRUID",
                spec = "Restoration",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_PRE_LOONBIS",
                name = "PRE Druid Restoration - LoonBiS WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37149, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42339, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 37673, enchantId = 50336, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41610, enchantId = 47898, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 42102, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37361, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 42113, enchantId = 44592, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 37643, enchantId = 0, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37791, enchantId = 41602, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44202, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 37694, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37192, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37657, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 37169, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40699, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 33508, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T7_LOONBIS",
                name = "T7 Druid Restoration - LoonBiS WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 44007, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40071, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 39719, enchantId = 50336, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40723, enchantId = 47898, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 44002, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44008, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40460, enchantId = 44592, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40561, enchantId = 0, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40379, enchantId = 41602, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40558, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40719, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40375, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 39766, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40342, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T8_LOONBIS",
                name = "T8 Druid Restoration - LoonBiS WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46184, enchantId = 50370, gemIds = {41401}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46187, enchantId = 50336, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45618, enchantId = 47898, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45519, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45446, enchantId = 60767, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46183, enchantId = 44592, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45616, enchantId = 0, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46185, enchantId = 41602, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45135, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45946, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45703, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45535, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 46017, enchantId = 60714, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45271, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40342, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Druid Restoration - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37149, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 37683, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 34209, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 37799, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 42102, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37361, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 42113, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 37643, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37791, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44202, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 37694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 37192, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37111, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37657, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37360, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 33508, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T9_BISTOOLTIP",
                name = "T9 Druid Restoration - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48141, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 45243, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48138, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47553, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 47096, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47066, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48142, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47145, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 48140, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47097, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45495, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47224, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 54589, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45535, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47958, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40342, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T10_BISTOOLTIP",
                name = "T10 Druid Restoration - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51302, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51304, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50668, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50717, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50630, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51301, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50705, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51303, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 49894, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50454, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_RS_BISTOOLTIP",
                name = "RS Druid Restoration - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51302, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50609, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51304, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50668, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50717, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50630, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51301, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50705, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51303, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 49894, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50400, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50636, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50366, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47059, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 46017, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50635, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50454, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_PRE",
                name = "Druid Restoration - WOTLK_PRE",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T7",
                name = "Druid Restoration - WOTLK_T7",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T8",
                name = "Druid Restoration - WOTLK_T8",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T9",
                name = "Druid Restoration - WOTLK_T9",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Malfurion's Headpiece of Triumph (H)", "SHOULDER: Malfurion's Spaulders of Triumph (H)", "BACK: Bolvar's Devotion (H)", "CHEST: Vestments of the Shattered Fellowship (H)", "WRIST: Bracers of the Autumn Willow (H)", "HANDS: Malfurion's Handguards of Triumph (H)", "WAIST: Cord of Pale Thorns (H)", "LEGS: Malfurion's Leggings of Triumph (H)", "FEET: Boots of the Mourning Widow (H)", "RING2: Ring of the Darkmender (H)", "TRINKET1: Solace of the Defeated (H)", "OFFHAND: Chalice of Benedictus (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T10",
                name = "Druid Restoration - WOTLK_T10",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_RESTORATION_WOTLK_T10_PROGRESS",
                name = "Druid Restoration - WotLK T10 Progression",
                class = "DRUID",
                spec = "Restoration",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Solace of the Defeated (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
