-- Auto-generated from wishlistBuildData.lua
return {
    {
                id = "DRUID_FERAL_DPS_CLASSIC_PRE",
                name = "Druid Feral (DPS) - CLASSIC_PRE",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_CLASSIC_T1",
                name = "Druid Feral (DPS) - CLASSIC_T1",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_CLASSIC_T2",
                name = "Druid Feral (DPS) - CLASSIC_T2",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_CLASSIC_T25",
                name = "Druid Feral (DPS) - CLASSIC_T25",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_CLASSIC_T3",
                name = "Druid Feral (DPS) - CLASSIC_T3",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_PRE",
                name = "Druid Feral (DPS) - TBC_PRE",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_T4",
                name = "Druid Feral (DPS) - TBC_T4",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_T5",
                name = "Druid Feral (DPS) - TBC_T5",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_T6_WOWHEAD",
                name = "T6 Druid Feral (DPS) - Wowhead",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 8345, enchantId = 35452, gemIds = {}, notes = "", source = "wowhead" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31048, enchantId = 29483, gemIds = {32194, 32194}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31042, enchantId = 27960, gemIds = {32194, 32194, 32194}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32324, enchantId = 27899, gemIds = {32220}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31034, enchantId = 25080, gemIds = {32194}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {32194, 32194}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 31044, enchantId = 35490, gemIds = {32194}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32366, enchantId = 34007, gemIds = {32194, 32220}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32497, enchantId = 27927, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29301, enchantId = 27927, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 30627, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 33716, enchantId = 27977, gemIds = {}, notes = "", source ="wowhead" },
                    RELIC= { itemId=29390,enchantId=0,gemIds={},notes="",source="wowhead"},
                },
                sources = {"wowhead"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Enchants from Wowhead gem/enchants guides.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_T6_LOONBIS",
                name = "T6 Druid Feral (DPS) - LoonBiS TBC",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 8345, enchantId = 35452, gemIds = {32409}, notes = "", source = "loonbis" },
                    NECK = { itemId = 32260, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31048, enchantId = 35407, gemIds = {23097}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32323, enchantId = 34004, gemIds = {23097}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 32252, enchantId = 27960, gemIds = {23097}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32324, enchantId = 27899, gemIds = {23097}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 29947, enchantId = 25080, gemIds = {23097}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {23097}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 31044, enchantId = 35488, gemIds = {23097}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32366, enchantId = 34007, gemIds = {23097}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32497, enchantId = 27920, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29301, enchantId = 27920, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 30627, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 32505, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 33716, enchantId = 27977, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 29390, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Enchants from Wowhead gem/enchants guides.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_T6",
                name = "Druid Feral (DPS) - TBC_T6",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_TBC_T6_SWP",
                name = "Druid Feral (DPS) - TBC Sunwell (BiS)",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_PRE_LOONBIS",
                name = "PRE Druid Feral (DPS) - LoonBiS WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42550, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 43481, enchantId = 61117, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 43406, enchantId = 55777, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39554, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 44203, enchantId = 57683, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 37409, enchantId = 54999, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37644, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 44297, enchantId = 55016, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40586, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37642, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 41257, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40713, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T7_LOONBIS",
                name = "T7 Druid Feral (DPS) - LoonBiS WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40473, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44664, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40437, enchantId = 61117, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40403, enchantId = 55777, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40539, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40186, enchantId = 57683, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40541, enchantId = 54999, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40260, enchantId = 0, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 44011, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 39701, enchantId = 55016, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40474, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 40074, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 42987, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40256, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40388, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 39757, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T8_LOONBIS",
                name = "T8 Druid Feral (DPS) - LoonBiS WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 45993, enchantId = 44149, gemIds = {41398}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45945, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 45245, enchantId = 61117, gemIds = {39996}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45461, enchantId = 55777, gemIds = {39996}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45473, enchantId = 60692, gemIds = {39996}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45611, enchantId = 57683, gemIds = {39996}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46043, enchantId = 54999, gemIds = {39996}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 46095, enchantId = 0, gemIds = {39996}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45536, enchantId = 50967, gemIds = {39996}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45564, enchantId = 55016, gemIds = {39996}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 46048, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45608, enchantId = 44645, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 45609, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45613, enchantId = 59621, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40713, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Druid Feral (DPS) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 40678, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 37139, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 43406, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39554, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 44203, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39557, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40694, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37644, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 44297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 40586, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 42642, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40684, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37883, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40713, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T9_BISTOOLTIP",
                name = "T9 Druid Feral (DPS) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48204, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47060, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48207, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48206, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 47155, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48203, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47112, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 45536, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47077, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 45608, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47075, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 45931, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47131, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47130, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47668, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T10_BISTOOLTIP",
                name = "T10 Druid Feral (DPS) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51296, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51299, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51298, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50670, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50604, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50343, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50735, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50456, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_RS_BISTOOLTIP",
                name = "RS Druid Feral (DPS) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51296, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50633, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51299, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51298, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 50675, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50402, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 54590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50363, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50735, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50456, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_PRE",
                name = "Druid Feral (DPS) - WOTLK_PRE",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T7",
                name = "Druid Feral (DPS) - WOTLK_T7",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T8",
                name = "Druid Feral (DPS) - WOTLK_T8",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T9",
                name = "Druid Feral (DPS) - WOTLK_T9",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Malfurion's Headguard of Triumph (H)", "NECK: Charge of the Demon Lord (H)", "SHOULDER: Malfurion's Shoulderpads of Triumph (H)", "BACK: Vereesa's Dexterity (H)", "CHEST: Malfurion's Raiments of Triumph (H)", "WRIST: Bracers of Dark Determination (H)", "HANDS: Malfurion's Handgrips of Triumph (H)", "WAIST: Belt of the Merciless Killer (H)", "FEET: Treads of the Icewalker (H)", "RING2: Ring of Callous Aggression (H)", "TRINKET2: Death's Verdict (H)", "MAINHAND: Lupine Longstaff (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T10",
                name = "Druid Feral (DPS) - WOTLK_T10",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_DPS_WOTLK_T10_PROGRESS",
                name = "Druid Feral (DPS) - WotLK T10 Progression",
                class = "DRUID",
                spec = "Feral (DPS)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"BACK: Vereesa's Dexterity (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_CLASSIC_PRE",
                name = "Druid Feral (Tank) - CLASSIC_PRE",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Magni's Will"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_CLASSIC_T1",
                name = "Druid Feral (Tank) - CLASSIC_T1",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_CLASSIC_T2",
                name = "Druid Feral (Tank) - CLASSIC_T2",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_CLASSIC_T25",
                name = "Druid Feral (Tank) - CLASSIC_T25",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_CLASSIC_T3",
                name = "Druid Feral (Tank) - CLASSIC_T3",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_TBC_PRE",
                name = "Druid Feral (Tank) - TBC_PRE",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_TBC_T4",
                name = "Druid Feral (Tank) - TBC_T4",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_TBC_T5",
                name = "Druid Feral (Tank) - TBC_T5",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_TBC_T6_LOONBIS",
                name = "T6 Druid Feral (Tank) - LoonBiS TBC",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    NECK = { itemId = 30017, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31048, enchantId = 35417, gemIds = {24033}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31042, enchantId = 27960, gemIds = {24033}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32324, enchantId = 27914, gemIds = {24033}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31034, enchantId = 25072, gemIds = {24033}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 30106, enchantId = 0, gemIds = {24033}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 31044, enchantId = 35495, gemIds = {24033}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 29279, enchantId = 27920, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 32266, enchantId = 27920, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 32658, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 30627, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 30883, enchantId = 27977, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32387, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't6' sourced from LoonBiS (TBC addon). Enchants from Wowhead gem/enchants guides.",
            },
    {
                id = "DRUID_FERAL_TANK_TBC_T6",
                name = "Druid Feral (Tank) - TBC_T6",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_TBC_T6_SWP",
                name = "Druid Feral (Tank) - TBC Sunwell (BiS)",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_PRE_LOONBIS",
                name = "PRE Druid Feral (Tank) - LoonBiS WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42550, enchantId = 67839, gemIds = {41339}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 43481, enchantId = 44957, gemIds = {40008}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37183, enchantId = 57690, gemIds = {40008}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39557, enchantId = 63770, gemIds = {40008}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 43286, enchantId = 50965, gemIds = {40008}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 38365, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T7_LOONBIS",
                name = "T7 Druid Feral (Tank) - LoonBiS WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40329, enchantId = 67839, gemIds = {41339}, notes = "", source = "loonbis" },
                    NECK = { itemId = 40387, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40494, enchantId = 44957, gemIds = {40008}, notes = "", source = "loonbis" },
                    BACK = { itemId = 40252, enchantId = 47672, gemIds = {40008}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40471, enchantId = 50963, gemIds = {40008}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40186, enchantId = 57690, gemIds = {40008}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40472, enchantId = 63770, gemIds = {40008}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 44011, enchantId = 50965, gemIds = {40008}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40243, enchantId = 55016, gemIds = {40008}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40370, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 44063, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 38365, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T8_LOONBIS",
                name = "T8 Druid Feral (Tank) - LoonBiS WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 41678, enchantId = 67839, gemIds = {41339}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45517, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 45245, enchantId = 44957, gemIds = {40008}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45496, enchantId = 47672, gemIds = {40008}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 45473, enchantId = 50963, gemIds = {40008}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45611, enchantId = 57690, gemIds = {40008}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 46043, enchantId = 63770, gemIds = {40008}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 46095, enchantId = 0, gemIds = {40008}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 45536, enchantId = 50965, gemIds = {40008}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45232, enchantId = 55016, gemIds = {40008}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45471, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 45608, enchantId = 59636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 46021, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45533, enchantId = 27984, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 45509, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Druid Feral (Tank) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 37293, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 42646, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 43481, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 43565, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 43590, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 37183, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39557, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 43591, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 43286, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 43592, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 37784, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 43582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 44253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 37220, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 37883, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 38365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T9_BISTOOLTIP",
                name = "T9 Druid Feral (Tank) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48204, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47133, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48207, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47545, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 47004, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 45611, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48203, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47112, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 46975, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47077, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 47955, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47731, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 45158, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47130, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 45509, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T10_BISTOOLTIP",
                name = "T10 Druid Feral (Tank) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51296, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51299, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50656, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50670, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51295, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50404, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50735, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50456, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_RS_BISTOOLTIP",
                name = "RS Druid Feral (Tank) - BiS-Tooltip WotLK",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51296, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 51299, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50718, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 50656, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54580, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51295, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50707, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51297, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50607, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50622, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 54576, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50364, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47088, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50735, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50456, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_PRE",
                name = "Druid Feral (Tank) - WOTLK_PRE",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T7",
                name = "Druid Feral (Tank) - WOTLK_T7",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T8",
                name = "Druid Feral (Tank) - WOTLK_T8",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T9",
                name = "Druid Feral (Tank) - WOTLK_T9",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Malfurion's Headguard of Triumph (H)", "NECK: The Arbiter's Muse (H)", "SHOULDER: Malfurion's Shoulderpads of Triumph (H)", "BACK: Vereesa's Dexterity (H)", "CHEST: Cuirass of Calamitous Fate (H)", "HANDS: Malfurion's Handgrips of Triumph (H)", "WAIST: Belt of the Merciless Killer (H)", "LEGS: Leggings of the Broken Beast (H)", "FEET: Treads of the Icewalker (H)", "RING1: Loop of the Twin Val'kyr (H)", "TRINKET1: Satrina's Impeding Scarab (H)", "MAINHAND: Lupine Longstaff (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T10",
                name = "Druid Feral (Tank) - WOTLK_T10",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "DRUID_FERAL_TANK_WOTLK_T10_PROGRESS",
                name = "Druid Feral (Tank) - WotLK T10 Progression",
                class = "DRUID",
                spec = "Feral (Tank)",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"TRINKET2: Satrina's Impeding Scarab (H)"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
}
