-- Auto-generated from wishlistBuildData.lua
local Goals = _G.Goals or {}
_G.Goals = Goals
Goals.BuildFileData = Goals.BuildFileData or {}
Goals.BuildFileData["Builds/Shaman/Elemental/Builds.lua"] = {
    {
                id = "SHAMAN_ELEMENTAL_CLASSIC_PRE",
                name = "Shaman Elemental - CLASSIC_PRE",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "CLASSIC_PRE",
                level = 60,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                conflicts = {"RING1: Songstone of Ironforge"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_CLASSIC_T1",
                name = "Shaman Elemental - CLASSIC_T1",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "CLASSIC_T1",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p1' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_CLASSIC_T2",
                name = "Shaman Elemental - CLASSIC_T2",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "CLASSIC_T2",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p3' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_CLASSIC_T25",
                name = "Shaman Elemental - CLASSIC_T25",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "CLASSIC_T25",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_CLASSIC_T3",
                name = "Shaman Elemental - CLASSIC_T3",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "CLASSIC_T3",
                level = 60,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-classic"},
                notes = "Phase data 'p6' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_TBC_PRE",
                name = "Shaman Elemental - TBC_PRE",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "TBC_PRE",
                level = 70,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_TBC_T4",
                name = "Shaman Elemental - TBC_T4",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "TBC_T4",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't4' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_TBC_T5",
                name = "Shaman Elemental - TBC_T5",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "TBC_T5",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Phase data 't5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_TBC_T6",
                name = "T6 Shaman Elemental - Wowhead TBC",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31014, enchantId = 29191, gemIds = {34220, 24056}, notes = "", source = "wowhead" },
                    NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    SHOULDER = { itemId = 31023, enchantId = 28886, gemIds = {24056, 24059}, notes = "", source = "wowhead" },
                    BACK = { itemId = 32331, enchantId = 34003, gemIds = {}, notes = "", source = "wowhead" },
                    CHEST = { itemId = 31017, enchantId = 27960, gemIds = {24056, 24059, 24059}, notes = "", source = "wowhead" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "wowhead" },
                    HANDS = { itemId = 31008, enchantId = 33997, gemIds = {24059}, notes = "", source = "wowhead" },
                    WAIST = { itemId = 32276, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    LEGS = { itemId = 30916, enchantId = 24274, gemIds = {24059, 24059, 24056}, notes = "", source = "wowhead" },
                    FEET = { itemId = 32239, enchantId = 34008, gemIds = {24059, 24056}, notes = "", source = "wowhead" },
                    RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowhead" },
                    RING2 = { itemId = 29305, enchantId = 27924, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    TRINKET2 = { itemId = 28785, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                    MAINHAND = { itemId = 32374, enchantId = 27975, gemIds = {}, notes = "", source = "wowhead" },
                    RELIC = { itemId = 32330, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                },
                sources = {"wowhead"},
                notes = "Phase data 't6' sourced from wowhead.com; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_TBC_T6_SWP",
                name = "Shaman Elemental - TBC Sunwell (BiS)",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-tbc"},
                notes = "Sunwell Plateau final-phase BiS from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_PRE_LOONBIS",
                name = "PRE Shaman Elemental - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 42555, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 42647, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 34390, enchantId = 61120, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 41610, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 39592, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 37788, enchantId = 55628, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 39593, enchantId = 55641, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40696, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 37695, enchantId = 41604, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 43469, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40585, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 42644, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 41384, enchantId = 59625, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40698, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40708, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 'pre-bis' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T7_LOONBIS",
                name = "T7 Shaman Elemental - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 40516, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 44661, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 40286, enchantId = 61120, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 44005, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 40514, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 40324, enchantId = 55628, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 40302, enchantId = 55641, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 40301, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 40560, enchantId = 41604, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 40519, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 40399, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 37694, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 40432, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 40395, enchantId = 59625, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 40401, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40267, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't7' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T8_LOONBIS",
                name = "T8 Shaman Elemental - LoonBiS WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 46209, enchantId = 50368, gemIds = {41285}, notes = "", source = "loonbis" },
                    NECK = { itemId = 45933, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 46211, enchantId = 61120, gemIds = {39998}, notes = "", source = "loonbis" },
                    BACK = { itemId = 45242, enchantId = 55642, gemIds = {39998}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 46198, enchantId = 60692, gemIds = {39998}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 45460, enchantId = 55628, gemIds = {39998}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 45665, enchantId = 55641, gemIds = {39998}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 45616, enchantId = 41611, gemIds = {39998}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 46210, enchantId = 41604, gemIds = {39998}, notes = "", source = "loonbis" },
                    FEET = { itemId = 45537, enchantId = 55016, gemIds = {39998}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 45495, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 46046, enchantId = 44636, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 40255, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 45612, enchantId = 59625, gemIds = {}, notes = "", source = "loonbis" },
                    OFFHAND = { itemId = 45470, enchantId = 60653, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 40267, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data 't8' sourced from LoonBiS (WotLK addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_PRE_BISTOOLTIP",
                name = "PRE Shaman Elemental - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 31014, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 37595, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 31023, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 41610, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 39592, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 34437, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 39593, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 37791, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 34566, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 43253, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 41384, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 40708, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'pre-bis' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T9_BISTOOLTIP",
                name = "T9 Shaman Elemental - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 48323, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 47144, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 48321, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 47552, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 48325, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 45460, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 48324, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 47921, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 47190, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 47099, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 46046, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 47928, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 45518, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 47188, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 47206, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 47085, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 47666, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't9' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T10_BISTOOLTIP",
                name = "T10 Shaman Elemental - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 50698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 50628, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51239, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 50687, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51238, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 50613, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51236, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50458, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 't10' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_RS_BISTOOLTIP",
                name = "RS Shaman Elemental - BiS-Tooltip WotLK",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_RS",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 51237, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    NECK = { itemId = 50658, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    SHOULDER = { itemId = 50698, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    BACK = { itemId = 54583, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    CHEST = { itemId = 51239, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WRIST = { itemId = 54582, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    HANDS = { itemId = 51238, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    WAIST = { itemId = 54587, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    LEGS = { itemId = 51236, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    FEET = { itemId = 50699, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING1 = { itemId = 50398, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RING2 = { itemId = 50664, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET1 = { itemId = 50365, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    TRINKET2 = { itemId = 50348, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    MAINHAND = { itemId = 50734, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    OFFHAND = { itemId = 50616, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                    RELIC = { itemId = 50458, enchantId = 0, gemIds = {}, notes = "", source = "bistooltip" },
                },
                sources = {"bistooltip"},
                notes = "Phase data 'rs' sourced from BiS-Tooltip (3.3.5a addon).",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_PRE",
                name = "Shaman Elemental - WOTLK_PRE",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_PRE",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                    HEAD = { itemId = 31014, enchantId = 59970, gemIds = {41285, 40027}, notes = "", source = "wowtbc.gg" },
                    NECK = { itemId = 37595, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    SHOULDER = { itemId = 31023, enchantId = 59937, gemIds = {39998, 39998}, notes = "", source = "wowtbc.gg" },
                    BACK = { itemId = 41610, enchantId = 47898, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    CHEST = { itemId = 39592, enchantId = 60692, gemIds = {39998, 39998}, notes = "", source = "wowtbc.gg" },
                    WRIST = { itemId = 34437, enchantId = 60767, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    HANDS = { itemId = 39593, enchantId = 44592, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    WAIST = { itemId = 40696, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    LEGS = { itemId = 37791, enchantId = 55631, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    FEET = { itemId = 34566, enchantId = 47901, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING1 = { itemId = 43253, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RING2 = { itemId = 40585, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET1 = { itemId = 37873, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    TRINKET2 = { itemId = 40682, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    MAINHAND = { itemId = 41384, enchantId = 60714, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    OFFHAND = { itemId = 40698, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                    RELIC = { itemId = 40708, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                },
                sources = {"wowtbc-gg-wotlk", "wotlkdb"},
                notes = "Phase data 'pre-bis' sourced from wowtbc.gg; item, gem, and enchant IDs resolved via WotLKDB.",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T7",
                name = "Shaman Elemental - WOTLK_T7",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T7",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't7' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T8",
                name = "Shaman Elemental - WOTLK_T8",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T8",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't8' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T9",
                name = "Shaman Elemental - WOTLK_T9",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T9",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                conflicts = {"HEAD: Nobundo's Helm of Triumph (H)", "NECK: Wail of the Val'kyr (H)", "SHOULDER: Nobundo's Shoulderpads of Triumph (H)", "BACK: Jaina's Radiance (H)", "CHEST: Nobundo's Hauberk of Triumph (H)", "HANDS: Nobundo's Gloves of Triumph (H)", "WAIST: Icehowl Cinch (H)", "LEGS: Legwraps of the Awakening (H)", "FEET: Boots of Tremoring Earth (H)", "RING2: Firestorm Ring (H)", "TRINKET2: Reign of the Unliving (H)", "MAINHAND: Misery's End (H)", "OFFHAND: Bastion of Purity (H)"},
                notes = "Phase data 't9' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T10",
                name = "Shaman Elemental - WOTLK_T10",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"bis"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Phase data 't10.5' sourced from wowtbc.gg; item IDs resolved via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_WOTLK_T10_PROGRESS",
                name = "Shaman Elemental - WotLK T10 Progression",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "WOTLK_T10",
                level = 80,
                tags = {"progression"},
                itemsBySlot = {
                },
                sources = {"wowtbc-gg-wotlk"},
                notes = "Icecrown Citadel normal-mode (T10) progression list from wowtbc.gg; item IDs via wowtbc.gg.",
            },
    {
                id = "SHAMAN_ELEMENTAL_TBC_T6_LOONBIS",
                name = "T6 Shaman Elemental - LoonBiS TBC",
                class = "SHAMAN",
                spec = "Elemental",
                tier = "TBC_T6",
                level = 70,
                tags = {"bis"},
                itemsBySlot = {
                    HEAD = { itemId = 31014, enchantId = 35447, gemIds = {34220}, notes = "", source = "loonbis" },
                    NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    SHOULDER = { itemId = 31023, enchantId = 35406, gemIds = {30555}, notes = "", source = "loonbis" },
                    BACK = { itemId = 32331, enchantId = 25084, gemIds = {30555}, notes = "", source = "loonbis" },
                    CHEST = { itemId = 31017, enchantId = 27960, gemIds = {30555}, notes = "", source = "loonbis" },
                    WRIST = { itemId = 32586, enchantId = 27917, gemIds = {30555}, notes = "", source = "loonbis" },
                    HANDS = { itemId = 31008, enchantId = 33997, gemIds = {30555}, notes = "", source = "loonbis" },
                    WAIST = { itemId = 32276, enchantId = 0, gemIds = {30555}, notes = "", source = "loonbis" },
                    LEGS = { itemId = 30916, enchantId = 31372, gemIds = {30555}, notes = "", source = "loonbis" },
                    FEET = { itemId = 32239, enchantId = 34008, gemIds = {30555}, notes = "", source = "loonbis" },
                    RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    RING2 = { itemId = 29305, enchantId = 27924, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET1 = { itemId = 23207, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    TRINKET2 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                    MAINHAND = { itemId = 32374, enchantId = 27975, gemIds = {}, notes = "", source = "loonbis" },
                    RELIC = { itemId = 32330, enchantId = 0, gemIds = {}, notes = "", source = "loonbis" },
                },
                sources = {"loonbis"},
                notes = "Phase data \"t6\" sourced from LoonBiS (TBC addon).",
            },
}

