        {
            id = "DRUID_BALANCE_TBC_T6_WOWHEAD",
            name = "T6 Druid Balance - Wowhead",
            class = "DRUID",
            spec = "Balance",
            tier = "TBC_T6",
            level = 70,
            tags = {"bis"},
            itemsBySlot = {
                HEAD = { itemId = 31040, enchantId = 29191, gemIds = {}, notes = "", source = "wowhead" },
                NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                SHOULDER = { itemId = 31049, enchantId = 28909, gemIds = {}, notes = "", source = "wowhead" },
                BACK = { itemId = 32524, enchantId = 25084, gemIds = {}, notes = "", source = "wowhead" },
                CHEST = { itemId = 31043, enchantId = 46502, gemIds = {}, notes = "", source = "wowhead" },
                WRIST = { itemId = 32586, enchantId = 46498, gemIds = {}, notes = "", source = "wowhead" },
                HANDS = { itemId = 31035, enchantId = 46514, gemIds = {}, notes = "", source = "wowhead" },
                WAIST = { itemId = 30888, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                LEGS = { itemId = 30916, enchantId = 24274, gemIds = {}, notes = "", source = "wowhead" },
                FEET = { itemId = 32239, enchantId = 46470, gemIds = {}, notes = "", source = "wowhead" },
                RING1 = { itemId = 32527, enchantId = 46518, gemIds = {}, notes = "", source = "wowhead" },
                RING2 = { itemId = 29305, enchantId = 46518, gemIds = {}, notes = "", source = "wowhead" },
                TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                TRINKET2 = { itemId = 32486, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                MAINHAND = { itemId = 32374, enchantId = 46540, gemIds = {}, notes = "", source ="wowhead" },
                RELIC = { itemId = 32387, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
            },
            sources = {"wowhead"},
            notes = "Phase data 't6' sourced from Wowhead. Enchants from Wowhead gem/enchants guides.",
        },
