        {
            id = "WARLOCK_AFFLICTION_TBC_T6",
            name = "Warlock Affliction - TBC_T6",
            class = "WARLOCK",
            spec = "Affliction",
            tier = "TBC_T6",
            level = 70,
            tags = {"bis"},
            itemsBySlot = {
                HEAD = { itemId = 31051, enchantId = 35447, gemIds = {34220, 32221}, notes = "", source = "wowtbc.gg" },
                NECK = { itemId = 34204, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                SHOULDER = { itemId = 31054, enchantId = 35406, gemIds = {32215}, notes = "", source = "wowtbc.gg" },
                BACK = { itemId = 32331, enchantId = 25084, gemIds = {}, notes = "", source = "wowtbc.gg" },
                CHEST = { itemId = 31052, enchantId = 27960, gemIds = {32196, 32196, 32196}, notes = "", source = "wowtbc.gg" },
                WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "wowtbc.gg" },
                HANDS = { itemId = 31050, enchantId = 33997, gemIds = {32196}, notes = "", source = "wowtbc.gg" },
                WAIST = { itemId = 30038, enchantId = 0, gemIds = {32221, 32210}, notes = "", source = "wowtbc.gg" },
                LEGS = { itemId = 31053, enchantId = 31372, gemIds = {32196}, notes = "", source = "wowtbc.gg" },
                FEET = { itemId = 30035, enchantId = 34008, gemIds = {32196, 32196}, notes = "", source = "wowtbc.gg" },
                RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                RING2 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowtbc.gg" },
                TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                TRINKET2 = { itemId = 29370, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
                MAINHAND = { itemId = 32374, enchantId = 27982, gemIds = {}, notes = "", source = "wowtbc.gg" },
                RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "wowtbc.gg" },
        },
            sources = {"wowtbc-gg-tbc", "wotlkdb"},
            notes = "Phase data 't6' sourced from wowtbc.gg; item, gem, and enchant IDs resolved via WotLKDB.",
        },
        {
            id = "SHAMAN_ELEMENTAL_TBC_T6",
            name = "T6 Shaman Elemental - Wowhead TBC",
            class = "SHAMAN",
            spec = "Elemental",
            tier = "TBC_T6",
            level = 70,
            tags = {"bis"},
            itemsBySlot = {
                HEAD = { itemId = 31014, enchantId = 29191, gemIds = {34220, 24056}, notes = "", source = "wowhead" },
                NECK = { itemId = 30015, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                SHOULDER = { itemId = 31023, enchantId = 28886, gemIds = {24056, 24059}, notes = "", source = "wowhead" },
                BACK = { itemId = 32331, enchantId = 34003, gemIds = {}, notes = "", source = "wowhead" },
                CHEST = { itemId = 31017, enchantId = 27960, gemIds = {24056, 24059, 24059}, notes = "", source = "wowhead" },
                WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "wowhead" },
                HANDS = { itemId = 31008, enchantId = 33997, gemIds = {24059}, notes = "", source = "wowhead" },
                WAIST = { itemId = 32276, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                LEGS = { itemId = 30916, enchantId = 24274, gemIds = {24059, 24059, 24056}, notes = "", source = "wowhead" },
                FEET = { itemId = 32239, enchantId = 34008, gemIds = {24059, 24056}, notes = "", source = "wowhead" },
                RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowhead" },
                RING2 = { itemId = 29305, enchantId = 27924, gemIds = {}, notes = "", source = "wowhead" },
                TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                TRINKET2 = { itemId = 28785, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                MAINHAND = { itemId = 32374, enchantId = 27975, gemIds = {}, notes = "", source = "wowhead" },
                RELIC = { itemId = 32330, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
            },
            sources = {"wowhead"},
            notes = "Phase data 't6' sourced from wowhead.com; item IDs resolved via Wowhead.",
        },
        {
            id = "PALADIN_RETRIBUTION_TBC_T6",
            name = "T6 Paladin Retribution - Wowhead TBC",
            class = "PALADIN",
            spec = "Retribution",
            tier = "TBC_T6",
            level = 70,
            tags = {"bis"},
            itemsBySlot = {
                HEAD = { itemId = 32235, enchantId = 29192, gemIds = {32409, 24058}, notes = "", source = "wowhead" },
                NECK = { itemId = 30022, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                SHOULDER = { itemId = 30055, enchantId = 28888, gemIds = {24027}, notes = "", source = "wowhead" },
                BACK = { itemId = 33122, enchantId = 34004, gemIds = {24054}, notes = "", source = "wowhead" },
                CHEST = { itemId = 30905, enchantId = 27960, gemIds = {24054, 24027, 24058}, notes = "", source = "wowhead" },
                WRIST = { itemId = 32574, enchantId = 27899, gemIds = {}, notes = "", source = "wowhead" },
                HANDS = { itemId = 29947, enchantId = 33995, gemIds = {}, notes = "", source = "wowhead" },
                WAIST = { itemId = 30106, enchantId = 0, gemIds = {24027, 24054}, notes = "", source =  "wowhead" },
                LEGS = { itemId = 30900, enchantId = 29535, gemIds = {24027, 24058, 24054}, notes = "", source = "wowhead" },
                FEET = { itemId = 32366, enchantId = 27951, gemIds ={24027, 24058}, notes = "", source = "wowhead" },
                RING1 = { itemId = 30834, enchantId = 27927, gemIds = {}, notes = "", source ="wowhead" },
                RING2 = { itemId = 32526, enchantId =27927, gemIds= {}, notes ="Use 'Band of the Ranger-General' instead for +HR", source ="wowhead" },
                TRINKET1 ={ itemId=29383, enchantId=0, gemIds={}, notes="", source="wowhead" },
                TRINKET2 ={ itemId=28830, enchantId=0, gemIds={}, notes="", source="wowhead" },
                MAINHAND ={ itemId=32332, enchantId=27984, gemIds={}, notes="", source="wowhead" },
                RELIC ={ itemId=27484, enchantId=0, gemIds={}, notes="", source="wowhead" },
            },
            sources = {"wowhead"},
            notes = "Phase data 't6' sourced from wowhead.com; item IDs resolved via Wowhead.",
        },
        {
            id = "WARLOCK_DESTRUCTION_TBC_T6_WOWHEAD",
            name = "T6 Warlock Destruction - Wowhead TBC",
            class = "WARLOCK",
            spec = "Destruction",
            tier = "TBC_T6",
            level = 70,
            tags = {"bis", "wowhead"},
            itemsBySlot = {
                HEAD = { itemId = 31051, enchantId = 29191, gemIds = {34220, 31867}, notes = "", source = "wowhead" },
                NECK = { itemId = 32589, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                SHOULDER = { itemId = 31054, enchantId = 28886, gemIds = {24056, 31867}, notes = "", source = "wowhead" },
                BACK = { itemId = 32331, enchantId = 25084, gemIds = {}, notes = "", source = "wowhead" },
                CHEST = { itemId = 30107, enchantId = 27960, gemIds = {31867, 31867, 24056}, notes = "", source = "wowhead" },
                WRIST = { itemId = 32586, enchantId = 27917, gemIds = {}, notes = "", source = "wowhead" },
                HANDS = { itemId = 31050, enchantId = 33997, gemIds = {31867}, notes = "", source = "wowhead" },
                WAIST = { itemId = 30038, enchantId = 0, gemIds = {24056, 31867}, notes = "", source = "wowhead" },
                LEGS = { itemId = 30916, enchantId = 24274, gemIds = {31867, 31867, 24056}, notes = "", source = "wowhead" },
                FEET = { itemId = 32239, enchantId = 34008, gemIds = {31867, 24056}, notes = "", source = "wowhead" },
                RING1 = { itemId = 32527, enchantId = 27924, gemIds = {}, notes = "", source = "wowhead" },
                RING2 = { itemId = 32247, enchantId = 27924, gemIds = {}, notes = "", source = "wowhead" },
                TRINKET1 = { itemId = 32483, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                TRINKET2 = { itemId = 39370, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
                MAINHAND = { itemId = 32374, enchantId = 27982, gemIds = {}, notes = "", source = "wowhead" },
                RELIC = { itemId = 29982, enchantId = 0, gemIds = {}, notes = "", source = "wowhead" },
            },
            sources = {"wowhead"},
            notes = "Phase data 't6' sourced from wowhead.com; item IDs resolved via Wowhead.",
        }